backbone: !!python/object:__main__.Rnn_forecasting
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg4NDgxMzc2cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODg0ODEzNzZxAWEuHgAAAAAAAABg63M9hIwFv2x3OD/kkNm+1scvP0Bjvjwg2z6+QC87vi7A
                    PT/4Rh8+Uj0HvyD1Sj3Ib3g/AEUQvXg6ub4gQmq+JDVMPxg28D7UtQS/DHIrv0A40DxASAm+AFTF
                    vuCr+T1IhsG+bIoGP3y4ZT903B4/wAqOPbAUWL4=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzU0NTU5NDA4cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTQ1NTk0MDhxAWEuHgAAAAAAAADWpHw/vg9CP3y5mj4otRG+7MpNP+AtWD1gFEi9oMypvSh3
                    wT4AR128GAuevrT28D7kfC8/YAMxv0DiGD6+fiI/yt4sP/Sl576QZwQ/BJLavrpqcj+2VWc/2s9t
                    v1iYN78wCRc/qGE+vlBkub4MBMe+fKtvv4gS1b4=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: true
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg5NzYzMDcycQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    ODQzMzg5NzYzMDcycQFhLoQDAAAAAAAAeNfPveEwNj64BoI9UhTMvVBlwL3we4S8YLnLvSw5gL2J
                    Mgy+hnoHPXBYrr0+GZ+9Q94RPmzr5r3r9yS9m/wcPuMDxL0d4Lg8HNOTPTjfyb0M6sE9YQUnPh0L
                    HL5dGGk8twO2vcWwp73i4568iaUzPhsEEL5aSsU9nfO7PQ2LrD0rkPS9bjwAPp5BDjxnlXq9eIAQ
                    Pl0eYb3ycbY9cdE0vnHEh72RFbu9iR+6veCRIr2/rsI9CJCAvfmn6rztc2a7VDZ6uyd+Hj6zXe29
                    Gf17Pcd5/r2w1RY9XK2dvcgukz0+4ea9hwwzvnLNAD0UF8C7/ZYsvg7a/718hFw9hWwmvqYeTLw2
                    0ky8ZHjHvf4NJz3Woxc+j8WKPTUONL3hdjk+T9ZNPdD35r1NqQs+MdVYPShQ2b38FGE9V7qCPVRo
                    3T2FIma9+XYqPkunOr28pMe9reR+vQi1RbwcPRS+PLVAvY12Cj6jArQ8A+06PsotEr5zq/o8n+mE
                    vZ2GsL1jgBE+YduAve+BG72TM4K9og/TvYxfnD1lEie+e7MdvmLIF74Pmvo8fQSHPI+Z1D2crO88
                    cc4VPjvsDr3l7yy+ZfzyPJvt/b23rDA+S0QbPRw5DL4o6QO+1E5JvaMLKL2np9g9MdHrPZnCT70r
                    pTQ+jtXePRnX/73ocEs9d+kFvgjGvT3G36Q8syoBvmPe2z2ZCDY7Kv6ePaTtNj30CQW+3/rUve6e
                    Gz4duO88o08Wvg6sLT1v8/i9f5mMPCvrCz5qa1i8Tumovco59b1ZB2W9eoyvPe+r5D3kiSO+r7UJ
                    PZZsHT54e7i8D3QbvZNinb14LpW9qPYivBaoLr5OC8S9BmkMPKLiTT0j9A29EzKcPANS971m/OY8
                    sLKOvXzK7D3wUFC9+CQhPl5GHT485vK9hseHPab24r1dqxu+29v7PW4JEL5RBBI+WGELvj0ZqLzf
                    8xo+S0iBvVZkKT6+k0c9uYGcvMequD3vzZi8/0/ZPHvGKz4DL+G9QIlzPb4hkD0dOVC9NEktPq2+
                    zb3imDU+ST4dPkXeLT5gRV09S1MPvbA0jj1EZUO90yWCvQKW2z1R9dI9yO8Avule6zyJOmg7il7h
                    PWKvmry4P0w9++3ZvROzf726AKs8kHybvbAL5j2jVqA9psQbvqLuvr3XW4e9ZMz3PQRu1bzEyTi+
                    Xk4mPkt7yL1cNTS+liUuPqi21L2nwgs90xWkPaCLFT6syDc+7aIWPteNQzs40hw+CU2UPTiR9bsP
                    xjC+MIaaPYiLCb7sba295r0XvU2E3D1GCSy7/5YcvvQwVz2LawW9onYwPjO/Qbw0iuC98OyDPOtx
                    MTzYxus7Ovg5vMeqvD0oe2y9fMwxvhzICj4PkLK9fDYKPl4GVL2WfoG9P0LnvUEYIr5E2/i9rd0e
                    PYkXML5mNce8H/4iPlgWKb6DLxq+XG/wPQ8kOT4MltG969MSPvWIHr7Ceqa9skwIPuKb/j2tNZA9
                    CJQvPFrDjD2yeBW+v7Uivq+mlb0eYbS9IfguvmRUUj34E969ghrpvKkBpD1N2Zg5x8MmvQt3Z70x
                    o9i8wR7Cvc3mzj0XoR4+R6aFve2Xqb3kn4O7ym8fvnKaGz7J2DS+UgZJvXsP7r2Oug0+RW0NPtDg
                    nbxck6k9Q30dvkH1kLxpVRA9GIqCPVQ3/T0H15E9Qd0oPUhNFj49zQU+QXBuPQKr9L3eOgs+Mb6a
                    veQxHL5fzi0+ueKKPOyHG767f0+9PH97vKFTMr6hMDO+NiIfvjyaar2AxIS9LZI7PYafDj4b/uS9
                    dQGhPVgtz7wiavq8fKUlPgC55L3sGaS99oizvbNQLD6yzKg9lfFNvZC2nj1UiQs+qBIGPgOUHD5z
                    17A93gPJveQ3FD64NGW9vztzvUKZSD3j5/E8fbxqveWLMz0fUpC9n93XvW5HML4n2R6+FAoVvQPc
                    kLyS0U891fgIO9QGwL3M5JM9Otvzuvhb9jw930Q8X8iMvDD0Lj5QjRY+zqjmPaO2FD4s9oQ8Sdox
                    vsCJOL49mw0+GMAYPkDZRT0kaAE+JBxivfDWnzxlC7I92rjdOroBLD4QVWc9bFwuvgy8Bj5e3RE+
                    7Mb5vXofyr0Km/o9tYU3vleh2z0sWzK+T6kEPsOeirxSmNo9CeH3vStwPr0QYsw8qIwuvib4/L2S
                    2OM8YyZzvfb2Er6c5zE+Wr2sPUWVv7rW91u97wxgPc7PKT2K5ge9RCxjPSQJjbw/7ZU83jkJvtPt
                    Aj5xkSc+JYzZPUqbBb2eC4q9LviyPb3g5rzUXb29gYC9PWB8s70Ffw89cATPvZm+lTyBGHG9sbzX
                    vI5owT3bZQC9AAy5PXUY4z3pVuo9ySlXPWKx/r2Xl+E9CI/gvWv67rnTtcq9fZSQvCcZOL4yha89
                    khiKPKcu9b2OkbM9Up0APtpUFD0Z3du9MRUoPsrJBr4n+Wc9U/FLvSL6Mj588ig+C8DoPbqYg73s
                    aLC96zy9PYQU/jzX/wa+gga1PUVKCD5UJ6g9J6rcvVJUEj5HD7q8DDYZu1OLPj1o/bw9Ih7kvLJZ
                    Mj6Bp+098omQPMlpk73rbiS+/sxnOvMoK77qTa090R1evHQ26b1O6Rc8l+WcPF6r6LzWOrg9TEoq
                    vp/jL77Kt9k8W7g7vIaF7r1FGG+80npHvN2opz3bpic+lsGivRSCYDxNMCK+FeOIPSric7uTXLa9
                    xdkuPlRwJT0aRwa+T+c3voQcFr4PK0q9bUw4PrWM6by5XeC9cswPPp4rZ716c/M8484WPmahg7yV
                    u4U8JQwnPsZaCr7uOJE9PtMhvvNH2L024Mw9CruOva2m6D3WaMc71LXWPOM8NT54mpS9g4OmPSwd
                    sjt0Yh2+hVeUvCDp7L2PWGE9dlJcPbLnyLyPQ6i9CBcsvkBFEb40QZE9QmUwPiXoHDu7nxS8y9qm
                    PWGspDqXUyK+EB+mvZyzhrwLd049DnvQvSc7ED5eDc49BDXJPCbGEz430kC5D6SuPSWiBr4EMpg8
                    a98VPt8e4L1J3fE9Oq6OPR//A74CwWo9d840vqAoMT5qj5+9Z9LFvYtY4DtqdHO9T6RHPYqmfb1m
                    JbI97ofNPTboEL6K+u09VLQhvp79sLxWNYo9OHHiPehHzzzFyg2+KXrSPJ0hCb6UO9+9et0ZPtCQ
                    hb2AnYW8V0ZtPIc/v72NxjI+qtkTvnC+4r1bAfm9O7PUvdrrBj7voB29gOrnPbAXrD20Ua09q/eW
                    PaviuDy3Qcw9yGSfvZldL75ugRW+dOhpPVcgu7344BG+NamZvI8N6jtLdP+9d7KJvAX5G73CMai9
                    pLLVvTb6gL3IYCS+qOotPjdH0D263ZU9Xk3RvUZd6b3iORS+eCH0veMxvrxjqwE+8AnhveCk+ry5
                    uCi+LYTNPPHjaD2eKm+6s9IzPnyhXT3/I1a9wqkaPv2z6j1S5/e9VJSFu2MBxD2W7KM9u5fXvR/h
                    Mj5fs6o9Qa4evYEVED5xJim9Q3+WvR2vDL6wRgI+VsIQPnSK8by8tLc7ShQ4PgrAj70FEUe9CHPv
                    vbVOxD3T2B8+kHzsPW2ToT0t9Sq9HKINPkGNUzyBYha99g1gvIMuLz51UY89az2cPSfkEj4M64u9
                    wPOKPf3UM77A6qu92B+svSQVHj6okPs9Pc7svfSs3rwiPXy9daAjvnL1z7w58Lg8x/bHPf70Ar5b
                    G849S//kPI3lqTl4JBY+sPSjPUi3Er4DDe29DP36vVvICr6xEby9MdGMvVQ7KD6Anas9RPEgvU52
                    wbxWU7G9sqKbPaWlNbzot/m98z7Wvahq7zwn2Oc96S/BPUlVxr2FjoI9PMjdvO3vAz1OeBg+3meP
                    PcALND5vAIq9qnT2vAS3kD2krRo+3joMvqwRrDy5JsO927i+PB+DKT4eXxU+km8tPtD/IT5riyA+
                    a03IPFO0uj09rtK8fvfbvZgSF77MbMA8FkEFvpMzQb1vOHy9LYusPckn+T0KMRu+FUDBPKtIC74M
                    ssq9xAoru3nK5D1AyBE+t3GgO7iK6L3SuwI+xswUPhtJEz3DeuM9B6ZMPYA9Bb4sbsm9nu8pvR4V
                    8rxl65Q9VepaPJ4vGL2Nqh4+3hD7PRAHbL3jZR69q8uavbWsP70xCtE9usMTPVsSjz1GNdm9RRFx
                    Pctxyr0tgyu9rSwVvI2Gq72KKg6+wbU2vr9gnT2beQ28y0L1PVUcBj5pjYE94E1nPahi6Dzaxp09
                    CBcZPn6AMrt1NW89rdCSvTLGjbxZ8Ka9vGfXvaqnKz4/ex8+U/wavjuajb1JOiU+VMe1POViurzS
                    bky93s4PPrCkKD55zou8IH8OvonEAr5SEdA9xtsRvVPq1L2yCw07+3v0vI61dbvUJ6A9I6kWvtzZ
                    HL4+SyW+FsbmNeIIpLzoODe+j9qEPeTZWz2R6JG9P62kvUSyGb7tAPA93dySPby1yj1lmyk+Kstf
                    vRBtTLt3VwE+dXJAPZSU0r3Bsuk9A6cdvo+tJT2e9xs+dlwQPsxuTzqGqcO9hQcwvkY1vb2t2x4+
                    121lvS85uT0NupM98yXBPcL6Mb2Y7gK+GUkgPtUpJT2GZXS8s5q/vQM0qT3RJwC+rz4aPsoJaD2T
                    uxA+g9Y3O7MSnjwAD+699j2wvMQUk72Z3Qw+jYEaPjzQSD2BHh8+OSoWvkbPAr5LHrY9mKrGPHv/
                    7T1znyS+dZUqvtBjjr05vWc9PYENPg5nmb33UGY94sEDPkOX1zzhyyI+GCsDviozFz7FvqY9O0aF
                    vTNncLw1H/M9Tp3LvSLfX7uGhL29TpYavkf/Hr6eSuY9
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzUzNzg3NDI0cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTM3ODc0MjRxAWEuHgAAAAAAAADX0is+bfd/PYNUA70qDzc9VhUJPd4niT1iyHK9XQImvSu2
                    nD1368k9lpMMvmMQDz5TPCK+1qOwvO+7GL5Z6Yu91Bk5PRibqLu8OXk8wKIvPseJuz1kZS4++Xnt
                    vc1ECz7Coxu+THSIvfSJuTuPcBy8PBssvXM0mbw=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: true
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg5MDQyMTQ0cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODkwNDIxNDRxAWEuHgAAAAAAAACvmZW9qofNva+DKz5XBsc97U5hPCyWGb2aYWA9FdikPTxQ
                    wD2+2dA9VVvaPFrQMr6fQYU6E3AaO2VeBT6g/P69W+6Wuy7CMb4jNrU9yk9nve69Az7CjuQ9umgZ
                    PhUoPT2zcbg9SjeKPB9kGr6/A4O8wiMaPr+BmT0=
                - 0
                - !!python/tuple
                  - 1
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg5NTQ4NDQ4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODk1NDg0NDhxAWEuAQAAAAAAAADCrWC9
                - 0
                - !!python/tuple
                  - 1
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 1
        training: true
    - - decision
      - !!python/object:torch.nn.modules.activation.Sigmoid
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  pas_de_temp: 2
  training: true
forcasting: false
learning_rate: 0.001
