backbone: !!python/object:__main__.Rnn_forecasting
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyMzQyMjExMDQwcQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    ODIzNDIyMTEwNDBxAWEuHgAAAAAAAAACSjE/kG2EPYACWrzAs4k8LtJoP4SV2L5ABf8+gCMfvPhB
                    jz4I+0q++IsXPvaOP79Y/qM+pDRfv0hX2b7gIV6+NoNIvzDepj0AaZU9cIgzP8gExT7AUNU+0JXU
                    vVzdnL6QZjW+ynVzvwx5C79A1Og+EPM9vpAUm74=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyMzQyMzg0NjcycQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    ODIzNDIzODQ2NzJxAWEuHgAAAAAAAADkZOq+WHMBv9QVjj6olyI+8Ho4PyRciz4IZHq+4MTsvdCo
                    zb6gf8y+APl4vUAxkzyAMcG8NEVIvzhSjz7MsIS+SnMbv6Rtx76Eij0/oAdAPSLqXj/gFZQ9UDqu
                    PmD3ab+wdSi+pAxMPyp0OD+iliG/kE1mvl6sOz8=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: true
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyMzQyMzE5MDcycQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    MDgyMzQyMzE5MDcycQFhLoQDAAAAAAAAvs8ovkYrgz3xkvs9ZrRHPczRtjwiriU+bwe5PTxjp70q
                    QEI98vM4vuufID7XGYS9WPT7PWw0ZTtHlvw9HSUAPSGDEry7Hfg91weNvcViaz2aQ849HMYCPmTh
                    HLxqhyo+s530PTGhnD3bwJC9cZiEvcKgHzzDlKy7O5KYPQETfD3+VjE+3IwRvSc1+j3gUCk+o5ik
                    vfpccDzqBPK6QfN2vSp/4r1fvXw79IYAPvnaOr53ELu98aIUPsJBoT1xrhU+KuyWu3CSCD6LyiI9
                    wfnGPYLaKT1CxP+8QH2ZO7p/C75SHjm+/J7rPeYCETxzHA++X4wpPktjOT7PzeY9PjM9Pdy65L0Q
                    VCy9KKLdvWUNs7yTODQ+Q3wlPlHVET7Q8Ak+201vPeFHLT4lQCC8fwDHvYZnFD58XMI9/QJzvRP/
                    Ab6w9+I87FxmO7XPxD0JtRi9qKVYOb0F0D3kx4s9/q5dPaUo0D2t5Yw9TsYmvrWbpL1JZMc9Pcgh
                    vt7UOr0E8dw93p8LPrl8+z3R+rI8dwIDvdJAzrzQueU9KByIvTqAv7xH9AC+kjmjPeYX7b0Qlzk+
                    7CcFvRpb2jz15wg+I8zovAHaBz6gxKu6BZQnPo/1aD1YGbu9FSCovQR7OL64ZEC9S2lSPdmlvz0W
                    RCC+7yohvjqVKL782Rg9AHpEPFWxBj5WoA4+btVUvfccvD1VGSe+Tw0vvuQfUzyisPw9BWC6vZV5
                    Ob6Cvf29O6UpPivzsb0i/Ao+gdf9vcHi3bzqduU9G6D6Pf1e7bxiERS+plsDPn/Xkb1Q0re7eILr
                    PPGnCD71T4M9fiv8vWrTqz20xlW8svUBPcyaBz6WFQA+PRsTvvEMKj3nhzA9AWebvPExFr10ZE08
                    4KYXvidUAD5tH9S9dCM2Pk4TDj7pSaY8c8cjPnkjEb4asJc98R42vVL4KL1cHV49XjU6vu42Nz42
                    HRS+xNtHPAAQwz1jY8W9TNAxvn3i7j088N49xJnAvYmGu70JmQ6+oogkPiZ7Qz2P8QE+2BTvPHpC
                    Ur237gm+HF4jPjl6sL13zDI+jjwIvVAQNr5ehDi9G5AePUiE/D2tDu09QiD6vaSEwj2YBgs+Gs8L
                    PmiRtr2WhTe9fVb/u81LIz7TC649Jcg+vFg7Fjxe4Ua8o8U7PT3B9byqRj293u0YvqBmDL1r4DI+
                    xFwWPrxsgj3joiU+X7zTPQcSjT2vwLe98A8APrSUpb1+8Jc9An4OvlVkDT7BIgy9W9MYPhl9mL2F
                    NjG+COKrPSoqlL3+1hu+2z2FPXLAN756dlM9IrE/vbMy6bwfLAU9Uwn3vYekub2V6zc+h4HNvdXt
                    Eb65Kxg+ZYcSPqSONTvafuE9ydIqPcX53T1qOws+ghIXPmUbHz4uUNY8jAYFvqDaFT0Ja1S9Gqfs
                    PQIbBTzh/7g8t6bUPZoJVT2jQlo8XV1+vUFViz2jT+k9+n1zPfC+Xjz4uqM8Ig9DO6S9Hr7paZa9
                    +z0tvg/kgz2iqnG8b4oMvQdF6T1vsgo+BoEaPo2p0r2FkBa+GbYuPuYO2b0S0cU9Z9YYvu7Dq718
                    sMa8X/m3vZzcCr05Fp09V0XLPLr1lr3hnSo+4WjmvJjoqD0fa3m9LiylPGGR1b1RbFE96FUEvn+b
                    N71f6gA+aAIyPi84+Tt4Rgo+0yBnPfjTA74WuXs97rNcPcOLVzz04tg9TGe1vTsTgD27aDO+FbGe
                    PZz8y70O1Qe+REz8PCG+Rjz1Wc69y/LKvUFyB75zoLE9qVABPtlT/r3GDhC+GczfvJ4+KD0A1AI9
                    njexPX4BMb5kIYM9dp4aPtk/FT0lYpS9yyEuPU44NT3AIxu+Bp8Dvh7DlTz/CYO7Z8gyvfN0+rwo
                    ZBc+ppvcvcmoUr13Mey9080gvELkbr1d0PM9PneJvUG+8z0fLCo+sWcoPhM/5L23zsS8NY+ROxiX
                    D77xBEI8GdrXvYvU9byG8ia+tdIPvYLJHj75Rdc850wzvonZ1zvBxwy9DaLOPdrZCr4hHrm9dli8
                    PU638L2hLOK9nVgYPnLu0b3YUCo+E+oHvReyKT3IH0I8xif1vcSfL75tFbM9crUmPdEK5b0KTAm9
                    o+fdvDhLvrzq+M88WX7OvXn0wD28QjE+z3blPXCEqr2soLI9H0xFPfR7L7208gG9oPLyPU15kb0n
                    jjo+wRAaPlBW4r2IuY29VBCmvVoGIr5UUcq9N/iyvc84Lb6q1Lu9C7mjPZX4G779F9i98hVbPcHY
                    Jz6tKXs9x1kXvk4E2LyyUeM7Mj4Ivle3mD31euq9zMX+vUZYF708o9+97I50vWRm7b0SrGA9AY9D
                    vYX9AL4EFwq+IK4pPgrwJD5U1Q4+O6i7PanlG75Sfd29a2ihvYshiD3Rmsu9rKbDvbMkBj2fDDI+
                    bLI0PpTR8jxHnGA79xCePAJQNr0Guq69W/4NPtEcAL40vxa+1yAXvqd9jLxeJlw8xI39vTKj1j2O
                    kUy9/ggrPo8TYrylNAa+1FFQPBW6YD1vzvO9HnoUPt1JqbzZIDM+tyhJvQtojT08mhk9i+7IvMaG
                    aT2WtkW8NV6FvdPMBz7ciDO8Fq7NvY5eOb7yJSU+ztrXPbrJAr5mdBY+kR2YvFGoNL7S92g9yn4f
                    vj3Bsr0u5pA9iRSovD5aXL2j6hG+IFMnvgrM9DxBTNa9ZOqQvRMFljwr0Bc+gbfuvSHaJb14nOo8
                    QipbvY30NT74joY9SkwdPa1rNb5q9zg+Qq+pPdm1w71pgY09tRtXPcws+j2NeRG+gSAkvpZAHz0J
                    TG69HavSPQrtK769EgA9+BYNvT6/HD6dNh++w9TuvLvIOb5q3ou9ztc2Pls2eT1QYQq+ClDqva4U
                    lb23CBO+HBmvPSSXE77PaEK9c6OXPS8U8714frE8MugvvNq3ML4GTvy9BkChvGKiQLy1+/W8MO6F
                    PYquCb7dIjE+C6gpPtsGAL62wgi+JZvtulhVCr0zgc69E24kPtY6jr332VU7s54avZAHtz3EUYw9
                    Xgk0vjvOyb3mWVG9xELlve5Eob1FSFg98JHOPcVdjz0eaXC8Q7HAvQUZxz0D1Ys9fq05vl+nDLzi
                    YCW+wNpUPY6T8D19hOQ9Iwy9Pfhn47z9xJg82isZvkTawb2OT6y9N3F8vYV6wrzYWSA9Cn2JPXPV
                    Mz5L7Ki8WL7IvWd0Aj5gMOa9n/8pPnApp71oKF68eEb5vBWCmj0D7Dm+Oe4vvKIb8r35XyQ+XWUN
                    PdmMGD1Lks69Ze6+u+3LZrrfHfm94JcFPgymjD1uAAy9oMhJPderVb03ORi+/3QpPINoaby6Tba9
                    RIK3Pem8Tb2Eczy9ocghPsRyk71RIxc+bru5vPZIAj7j+yo+Nv4nviM0OT5oXDY+Fs2sPd+AND7f
                    8c68HonVPfJHsL3HseC9GjDnvc8YEb4qVtQ9J9FxvKwpwj1w/Nw8SYBfPcIfpj3RRdm9GPvkvDJT
                    Yb384TE+nzpxvYVwS72cyAE+9MoQPgmrLzzEmgY+4hwvvrdQED4UTDi+Ln2KPWjHnD03oJ0918qG
                    vRY7Sb0eH1s9D+MEvorS2TwsbHm9NjDePSr6Nj67Mck8m3Qsvp4vFz4Lq6C9zNfcvY/Hrr0t2SA+
                    /FouPipVoD3bTrk9iYnCPPYiML4w2Lo9tnsbvvueK76eXkE8w62hvVByFz67Wci9BKOXvYz5uD3s
                    OFw9trwavvUG3b3H8I89gUsUvvAYM76bQHk9tpswPbwuGr6JVpk9tw3lOnOeAz7mMKM8sc4EPevG
                    7byzLRA9oLsIvo/DVz3PYJS9IBwqvhh1z73qWQ++eCbtvUGRBL5ZhyO9P8V5PeHy9j0c8809ar8a
                    vlLbCb4JWCc+nxIZvpSazz1GtIS9OmuGvcMfMD6O4WQ9nkGOPdQsJz1GXf487e26PGpAxT2DlDe8
                    HEu8vdi0Lj62zA2+FpO0Pey7vT3BNie+iTgnvH4yAL4a5Xw952vivcNVMb7EJUc9bbbNu4KSKb5l
                    fnI9q+YhvqHlMz1cz7A9RJfDvWsXEz6p/289KPtUPbNh/r1dSoK9UN/CvSHY7j25Fw09J30lPt6k
                    Kj3aG9q97g0evp5tXD1xPja+eKSgOU8Tkb0SUHc8Ku8uPgLnoT0EN/S8kRolvmygKL7gCnq9s4MR
                    vsK0870x2b29thbcPFnlKL68Z6i9yDvovaKKKj5HikY8Gv41vAekKD5cyxY+NOl6vXPXtL3jFyM+
                    EtKMPWeqOD5AzSY9IqcCvGjhazwXozK8LyEqvdG0MD0e8Dc9vaD1PHJQ8z0R49c9ginjvZCJYzxf
                    sCQ+QOpvvWizpL2cvDe9t7gWPsZkwL3ATNu9/VPRvL5CEb7BHz27Rq/RvD00Kb6PFdg8y+04vixv
                    Wb3lMjG+AU+IvSy6Nz6i02S9C+q5PZaDxz1XySE+jZsZvmA22Lxg7xq+B2TlvJolM77jh5m8B+3U
                    vKpNDr7isf08rjXbvV427r0rTrG9SpegvR7TIz5eYj291JoNPgJgrD0myq49jjD0vVN0Eb27Ups9
                    DaPwPTDwFj5Vrhe+8uB/vYDNuL2eRJW9vGDHPb10jrwR1dg90O4evkAbhj2tJSg98kepvWsPKD6p
                    OMO97DQsPombwL1ql4c9GNwDPb5G3D1Wbd29Y6LWvaianD2VBjE+CcyTPTTAaD2DChO+rxmJvVT7
                    8T29xjm+qg+svUZOGD62gMi9VSUkvjJKybwTJ8094SlGPaXvK776BQA+uH+Qu7zv2D1uDBg9MUHC
                    vF8YhT2AIIM8Rf4YvjQm5T08Oje+dlzQvTeCMD4uk9s9
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyMzQyMzE3ODU2cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    ODIzNDIzMTc4NTZxAWEuHgAAAAAAAAD8Z1M9Pu9+vTMlfr2prwi+ex96ve60Qb0zDrG96LSCPXSM
                    HT59B1S9hbvqvcCJqD3NH8G9H/SdvCK4OT6TeLq7UdTgvUcwBb0rkSe+kTZJPD2fXr1aBak9DrLo
                    vVYhBr6iJZs91usWvpggpz1/Uwy+0LxLPYiCZrw=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: true
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyMzQyMzg1OTM2cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    ODIzNDIzODU5MzZxAWEuHgAAAAAAAADgPcu9BDtBvPLBcj1jrX09otCePZaEEj5tpy6+Br3bvf7U
                    Dr5PdVw9UGpkPNhL/L3+yqc93xnNPC90nr3wrrq8KKNGvV30nj2FHxc+SJIpvmNBrj3wSpW8R27t
                    vURZjT3Uf1+65L0HvN8p5j22w648UITNPPmZJD4=
                - 0
                - !!python/tuple
                  - 1
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyMzQyMzI0ODMycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQw
                    ODIzNDIzMjQ4MzJxAWEuAQAAAAAAAAA3UjS9
                - 0
                - !!python/tuple
                  - 1
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 1
        training: true
    - - decision
      - !!python/object:torch.nn.modules.activation.Sigmoid
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  pas_de_temp: 2
  training: true
forcasting: true
learning_rate: 0.001
