backbone: !!python/object:__main__.Rnn_classifier
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzUzOTQ5MjAwcQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTM5NDkyMDBxAWEuHgAAAAAAAABubSs/0LpKP/4hZL9ojvu+ADFkvwCg37kIOhW/MHgSP+AA
                    975usTi/sMWWPnDJkT4sE9M++Mh1PrwaKD+k0hk/6m8GP1KYOT8wiMa+EF19Poja27445Nq+8HKa
                    PdBQHr5AmIi+VkxQv2zTP784HH8/oOFbvQA3eT0=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzY0NjM4OTc2cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNjQ2Mzg5NzZxAWEuHgAAAAAAAAAA0oA97nkXP4b8fL9MXmA/YKQtvaijSj5gwzk+cjE5v7Yq
                    D7+gcqw9toJ7P0Ca9j3APFu9xEJIv67rNr90+y2/uNNWP/Rg1r485O4+IMZhP0gVHL8Ey9O+QD+o
                    vEwrez/QROO+VAESv5RFVr+YVTy+NOBSvy58GD8=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: false
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzUzODYxMDQwcQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    ODQzMzUzODYxMDQwcQFhLoQDAAAAAAAAJ9eDvcErzr173Yy9A5lVvTySFb5abaq94yu0PcosIz5d
                    pgC+7dAju5JRi73l3rY8/31dvUNY6D0PZ2A9lUcmPuugJL4bM289NdQbvhvIED6gesA9qcPaPdf2
                    Mj4vu/A8PKwXvD/LjzyAZhO9ccRpvQb6hr0w2Je8xN7GPA+WvTrc7dO98+zKvbUjtL0I5O69czce
                    vpKhG76l6yQ+6S6CPZx+AT6vEjw90S7MvbzOB77S4wy+WVT9PRF4Cr6Ish28glAxPgrFoT1mJu09
                    +hqVvQSrzb0VzOU9b/Y3PsUaYr2hALS7uccePn0dvL3Ijgk+N3zSPaRi2T0YDZ29e3btvSMh8Dxo
                    IRo9ziAePL43ED3osxE74HMCvk5mIDwnbEa8Gh8avJ8WCz5qq569pxhLvDVC3zxcohe+kx8mPkl9
                    qzxERSs+f1iLvbC6Bj6PmOc9gHLivLPXRb1nil49GDQ/PS3YAL5nipC9YdU2vTMurD0IdxA+K9O6
                    Ped98b3Z+Fe9sgySPXzsHb47Dma9BBy4PZFeqzzw5hm9Jhc6vgbdXb30OA4+xt2mvd0QKD4QwlO9
                    bHMZPm+6eL0cGH28yuvcPVAibLulhSg+a4M0vYgDB714igI+seutParvGz51kSU+UcemvUyXKT6B
                    Bp89EA0IvvaM4j0diSK+Bp7jPSuMpb1ZztW9VVAyPpALGD0scZQ8ml0NPfQ2FD255YY8Q4ctPhDp
                    pD2DQ+q8aPdPvVrYIb5ZzRy+rDQJPRuO7jzk4zG9RSHEvQl3Lj7x7y2+dFMdPr3R1T0qDEm9x1u0
                    va44B70QPiq+7gCnPagavj24Qya+5+NnPaB3Kz2sTRO+Ei4EveE50Tyee4e8YZiXvRg/Ab6mwyU+
                    nHZZPQtvoz3/QwW9X9c2PooHxD2CF2W9QpAavpRcvzxh1HM8wvDMvQLinL2z/NK9E/QEvh5jAD5k
                    /Ru+qvoVvvB0ojq13Vi9FgA5Pq6LKb77nRE+ARuyvawUJL4fq9g9SAUFPaAY9z3leTE+51lZvatG
                    qT2t5BO+xKGVPWm/Kj7TVdU9zmqFPSquJT5uFtK99CmkvcvLD7wuHpQ9wI21ve5rJj4LHiE97Asz
                    vtOepT2KoA6+3zXGvbYP3j24E6a9BMMMvm7iLj4r7f+9Qkq9vZVUub3lbqq9bEBdvSEaHD4Fqjo+
                    wT8VPtW1Yb1GCiW+6jEHvhliz73nryM96cQnPms+4r0eq/M9gqn3PRGmzj20s7y95U4GPiUywD0v
                    +2Q9vv4WPpIlK75ZTgM+3/uzPUfp2b3wdSK+nLUHvoeyVb0Q62g9IFznvW9xuj3Liiw+6B84PuXU
                    OL6sXb49z4APvrJUEz6v0Rg+h3M5vnvwWbyioeS99bk5PlEUJL5wU2I9I6OPvQl+5r0k/wu+mq+0
                    vdwvMT6jGVk97WekvQXCAT4tkjg+voC8PaISFj4h7d494KSUPU50q72q/k87Cucqvoysp72nFgE+
                    TvgVPs4L5705Z5g9PTytPQBYMD5m8lY96tfMvaOcJL5O4m09OlmyvV4D2z3wfu08VLm/vcolYD3T
                    ULi9qO30vewchD0dsAQ+pPLXvav6Ij613KE96vUevfUw7j2vlw09m+o2vsLx4L1HjB4+dzmNPTpf
                    nD0GphI9AmsWvryNJ77tG5W84HcDvtMwKr4OqCs9K7o1vtSLMj4OKv89V7bKPTS2y70F3Cs+DfmX
                    PSRh+jyFVA++fmgsvqAvpb2pr/M91U8PvhA4I71Z0VE9CkxaPOu98j0pWje+p1vJvdsK9L0RH4E9
                    +3PGvctCHb7Ug+S9CHsmvkTPmr0Fuxs+SL3IPYrSLz7erh0+jwL3vXxwob2KQSs7RK0nPQqCAT7G
                    7No9f48EPlygrj243Qm+oyAUvY3Isr0Vyra9ziRuPU5P9r3S3Do+txvoPQvJ4z165he7I2JDPROO
                    Kj7s2QC+y9ySve+i2r1GLhO+446CvbRPKb1FTMw9VbShvSqiuL06OzU+C2usPc6AJT3c2o29myWy
                    vSH5yD1q4sI9DTSBPNfXAb4Lx9w9A+yYPGdDED4lI9A953QnPrwTlb33XzO+xk3BPDDScDom6dC9
                    sQUQvR6o6b2lKNM90E/DvS5CxL2eBvY7nAHivXzw2j0oXeU9ccW6O08M+T3Yuvc9yhWyPQIlab2i
                    7IG5odEnPgWb2L1z0co9T5cWPmFg8b2F/X89DXd3PWJaELxZta49mlN4vGpHpz3+CiA9NGaFvRFS
                    IL5GQlo9Hl7UvISyAz2JuBS+18PcPFNSp7xuqK49t/c5PjbNCb4k3G06qH55PSzYgDxG+M+83KsQ
                    vpd9qjwakt09O/YyPXd8Jr4XUza7pPZOvfSYBrzXmHC9PeeXPQQK6zzsFRu+Q+3VPWuSf70yjR++
                    eMA4vpwWo71UlOi95AiVOtIrUbxW5I49UwUYvvYXDD1qKfg9/L5Nvb559z2hLSy+xpcJvnzuDD0t
                    BLM846YgPiG6uT3oG1I9XnY4Pm4xOj6pfrQ9oGYDPmbY6rtb3sO8cHnKPYYaGz4nyqw9tMowvqOj
                    Mrz1gQ29Zevpvb9nZb3AMOo9bQWPulFXv72asy4+IQruvWrlGz4GtEs8y7ZmvZ90ET31XjM+10qI
                    vYUUmT15zS2+PJIrPNgx5r0Y8R4+52nhvHO72D0yzHK9xiGFvXfbKT6XdpA8B829vYMxBr7AYHK8
                    p5OMPFyiyr2Gd9k8TGYsPsv+D76rh/E7XRqxPSITOD5PEN+9B1R2vDTl9T0db5I96jSKPccfXj2i
                    DQI9veEePjZBOj32uQI94TGVPI+NOb0xgxO+H7fvPZJrTT2GQHK9B1novcIYgb0SOsY9d4ONPC9J
                    0j2oYDe+USUVPsuYqrzqE+k9U6/gPVehlD2ashW+lF+UPRK3vT0dhe69SM45vbCuED1+kKE89ZyY
                    PAbToz0NUwg+KvdqPc4fKD5PDiy+pVgZvTefFb7U4n69OiE4Puwjpj2UFPQ9I2EvvUrraD163t48
                    jZoqvdN3DT7y74m8EBWMPftqJT4Qi6m9Q6oKPpHLOD5Pd/k8SDfEvSXv1T2T6TK+R9StPdK2Hz5B
                    log9J42tvGGqGL7qVLY6KxCQPG3bEr0IThq+QBM1PgDPE71+Zcq9vTOivVHSrj1hoS2+hQ9UvLqC
                    Gb1kTY68oiL0PXFinjvQ5d28xXVePWLq5j2MjL69q2UaPbnmCL561Ck+79gjvSFzCT6XsSo+/tvQ
                    PQIhL7xALja+AYDvvVYgrL0e0Ku9UGgSvguG3j2Yqik+fPj+PfkZ8D1ZmBG+4P03PsGEkbxT0sy9
                    zDugvZxchjsN/0Q95suvPfVofjv46ye+VY1MPbgsbDztMRk+oYiavUD6DL7FYy47ShK+vfGaOb5M
                    dwU+9pQwvt3E971NPj49+DnXumFBhD2BTCe+mfYnPplLmL3rXg48dqnTvEIzLz7j4hW9/GuDvYr/
                    Kr5gdTQ+u6cOvpgPEz0pK2c9wQoNPuj8FD7FuAC95RCovdAEJ77JGYi9KtC9vC6rFr612sS9oO6f
                    PbCEOLxBDti9SddyPSSwfj2wwRS7QTZnPRsVnbx+GNG9K+ZCvcye6T0+SgC9XIWYPYdfAb2mZMc9
                    vRD6vSX/qDtmFh48tLKXPX8qwz2DELc8a/fPPQtlnr0UVzO+OogsvkBuzzydFcI9fqnkPTENyb3X
                    dGO9yY2HPfQnMT2nNCo+A3W1vSrgr713Dgo+ogQdPqq0wT1qGDK+e9DHPcCjnL24s3a9VSU5PqYB
                    JT6ePYw98usevpWxtb0SAww+8RYWPj9osz2j7Bs+fS1Zu1ArKD6qkJ49JDgXPtt6Ab4k1da9JVb0
                    vIisDj56Ie89OcLFPBefkL1idL8952Xfu/PRbL3bHH09weQ3PG1p/r19sAU9JdUKPlBXeTwvBZU9
                    alSdPKjq6j0btyk+M4zZvboiij2U/q08gBvoPQz1Vj1Bvyw9hR7rvcSBMr6Nx9q9y6G6vWpfyL3L
                    cjC920AOvh5QDz4+XrS9v9nGPZQFDT2kljI+3YEfvtxR7z2fVps9kL/vvYVqAryqbwE8NchjvZ7g
                    NT2l5iY+wcQGPnIiA75wGlM9Q9YrPoiDHD5onDa+7lyCPfbD2L1QE3W9/fX1PVrxgj1a8QM+DoG2
                    vF5fhD0AhzM+stbJvZmHxj36t429oZ/YvR85TL14IuC9RwCcPdYHgj2x5bQ9dG0vvjOinb1bLm29
                    NoPrvfh0Cj6lS6a9fBsFPjYu3T1AQoK9qw8pPqI7Nr7c7mQ9GIhZPW1N4z0a0+I9oSGjPTgQBL1r
                    8d49TQFluqaWFz4MEbe9NMcJPuMxQbxgekA9WCAivrbNHT4EKAW9YGYxvjaH1T0UWlc9zprKvf7N
                    4z06WJC9huaYPUMLJr5F1Rg+hEkKPtbkAL6tbUS8AdcmviJgGr6blAe+bK3FvTt3k7xhEiw9h82k
                    vRreIL5d5GQ9lsgUvhDvHL0T94g9fHYPvURNo71hVkk9z6T+vdCKG70Dg6c9UWVvvaI17b3B2xe+
                    1v62vZWWHL6b7C0+fdoyvofP9j1XXIM7Q6XPPcbxFD2ieZW85EaWvZa4Gz4joOE9MLbiPHeDUL3R
                    uAM+SGbZPR2iC75GXvY9bu40vOqvwL2QZoY9sn3AvaasxrxXe+g9K20NPZO6pD13UyA+hKENvp8R
                    IT4NKge9BBkTvuhiUj2wrSM8RwI2vnCQJT5eYyQ+PgyNvGlHkTyqTxa+bYVIvQTyDL6mPNM9GM0f
                    vjAByb0HNea8A0CavKqm9j0JI+q9nPWDPHRzHr5vI029
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzY1MjM1NzI4cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNjUyMzU3MjhxAWEuHgAAAAAAAAAOBSU+REawPWk0KT1ssQG+AQY2PrSNqjuk+Gg9xjdavCtz
                    Cz7yJlC9IgIQvX6EzD0MtA2+lHq4PZ1x0j03WtQ9hmHkPQ+4qrxmj1Y9sGocPt0H3r3a0/I9YQNf
                    vYG53b1+1A6+y3javcPoBT4mVFm9cUEEvt14Pr0=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: false
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: false
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzUzODU5MjQ4cQJYAwAAAGNwdXEDS5ZOdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTM4NTkyNDhxAWEulgAAAAAAAABIocy9fSwCvReYdb32cdC8KxwnPsex9rzDFRi8XCZuvU4J
                    fD1cCqK9BUIBvDbQWT3TIv29YtQcvYwtjzzCvlg8TN8APpMXib1vT+m9uxWqvafxIz0OJgI9DY2p
                    PUnSAD1IsRy+aE0YPg9KBr5pVlk95qwbvlFR+z3WpRS+dKYDvp6Mij20er899pU7vfTFiTyDuiY9
                    daARPiPlmTys9IK9gvMbPgswXLzQeOO9ll7JPfFD5j2dtNA9LCbmvaj6Dr5D1Ms9woCFvVn6CT78
                    2ps9KWJAPQs1vT1sLaE9TqEnPqg5OD49Tgi+I+W9vSHZg7zNUSi+zU4ZPhSpPLvuJ028wWIpvn+L
                    Hr0rXgg+XNhsPWtAdD07KNm9SIL0O7ms4bypWOE9/SnPvSdVCz7frDi+Ym4IPqCwZ71fBx2+HEsO
                    PYL1zT3zcR8+UNeNPD2kWz0oLXG9Q4Etvkm66j3/Fxm+l+zWvfYpvD0Yzko9JQFcvdt92D23biu+
                    Bj62Pe8TLr5HYMq9+xY6PmrPEDx0dSm7mf0xPkwZDb0gI1+9yescvsuS+z2rQD+9d2ojvjVXMr2d
                    kAc8NPSlPRjl9r2vbdg94sggvmCqgr00TK08NxoxvXiCAL6JTVM9G4VTPWNwCrwE9qi88leYvdk3
                    N76U9P29JHb0PevcHDynkMg9ru6TvfjcHD7kpji+V4/kvVTmNb6eDxq+J/QAPeHewj1vXMc9IkOV
                    PBcsNT66zuc9drbbveTc1z3zhYU8fxu5O0LqIz0X/Yi9/rUKPp9W1D191m89zEOEPXVZeT0=
                - 0
                - !!python/tuple
                  - 5
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzU0NTc5MjY0cQJYAwAAAGNwdXEDSwVOdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTQ1NzkyNjRxAWEuBQAAAAAAAABUtlk9Ws3lvenIkD3tOTW9ot7AOg==
                - 0
                - !!python/tuple
                  - 5
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 5
        training: false
    - - decision
      - !!python/object:torch.nn.modules.activation.Softmax
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        dim: 1
        training: false
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  training: false
forcasting: false
learning_rate: 0.001
