backbone: !!python/object:__main__.Rnn_forecasting
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzkwMjYxMDU2cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzOTAyNjEwNTZxAWEuHgAAAAAAAAB0q5m+6KWQPmxKab9sgKS+iFtlvxRcQD8o2rw+7MP/PlBm
                    wb7agiM/BBMFP1iTsD5QNuy9NEr9PqC6Br0ooTo/4PpDPrD/w75w9kU/2CJdPzBLfj7kxw0/fE2K
                    vphqMT/gpeg9nsEGP7rbRb9cO9E+mG4ZvwSF7L4=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg3OTQ2MjQwcQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODc5NDYyNDBxAWEuHgAAAAAAAACA8sC8+DVNPhgkbj48KBU/CKY4v6SDlD5EXK4+sEIGP3yi
                    zb5WYy4/ZEuPPoAgATwMR1i/oIygvrgXJz6oCBy+sKhIvn7RXL/Mmy6/VNJLP5DhBj5u9m8/ZJFg
                    P8ggEr4490++lJVuvy4XDT+c3Qm/QERAvUqIUT8=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: true
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg3ODY4OTYwcQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    ODQzMzg3ODY4OTYwcQFhLoQDAAAAAAAASGggvm9JvD04Kj49xIn7vQ3HSb3gUrq9CvHHPeeY3T0S
                    iAi+Kmw5PoMBsj2EJwq+MNyOvcJJ3r2P+Ii8Ak0vvoIYGL4H4C++lBX3PVIBGL63Urc90pQYvsvm
                    dr3TqCa+YCoMvnY+J74ewM09M+KDvXxpQ71iT2E9l5Oqvb+8wryjMRc+veVbvACLWLuDNBC+IO0B
                    vgO0lT2znjo+EVB9PSGTpT0YdBI+fbYZPF5Z0709waQ8eL6CvSTKpb3m/dK9+nHnvatNLb7I9fS9
                    PDXpvaPm2j3ZjqG8t40HPQIT0z3e38W98QoEvqUam7wz5RK+W0wSPsJmP73p9Ju8t3SuvZ4F9D1q
                    yUW9m1kRPpo3+T0h4cc9gsw2vvW+ET52pvM9koirvSXZA76DtJg89RA2PgzTtLxrbiK+8y4IPXj/
                    kb2k1RS+V73MvU06KD5gpgI+hjAzvsKnubxTNyQ9Kl5+vTp6B77Y+3I9IcI6vV+4Mr6Hcck9g0YS
                    PFPe2b3t9kS9caEhvkonTby/Op89Zst6PJKnJr3bISm+H7f3vWmwwTurggW+95oyPiIF0z2ulQU+
                    dibZPNgtOb5uB9+9zjT5vUxTsD3m3ho+8LWmvTYDyj3LlBk+PZf2PR0fhbvC+Ls9bnJ7vZgp872y
                    1gu+vyzOvbZQIz4ZKq69dWOGPQGIgjuNPBI+zn0bvrg74D3nMNK80oOtvTvwrz0h4T88mtEZO7KN
                    5D1MyQw+LfgZvsJa9r2aTyI+DMrcPOC6iT1gwVy8fkygPb/cB70Mbgk94hYyPkvVqT0qTjW+ns0j
                    vV3OHj6os9+97dnpvWhcZT3P/eE98k0uPsFDA74855W90rIBvnNL5b19WgG+adMZvqJGKz4JrT48
                    +5k2vr2yKj5mLji9R2L1PdSXhDt0EW69Xak1Pp4+r72sapG9K7vZPHy4Vb3H7I09FPVEveqzrD2s
                    aZq9ktGwvYz1Iz7XTTY+5yr2vTO7uby7eoy9zE7xPaJD4r2Ir+g9Rmgpvrf0Wr0EZyK+6U+QPWWI
                    G72wZ1k9XNWUveCknr2LCh++2VFFvSL9uT1Y++88/GgcPI2lRr2FSPQ9z1sePqyHNj6P18A84JDm
                    PcaiSzzCSwY+DeM4PpURKT5UExS8R7M0PkPjir0gkYY9cxzivYqfKb5EZRK+urbHPREbTD2brzA+
                    PmQRPuZvIz4twMc9rAynvLZ/ML1GoPI9EJ/Lvb9Hq7rdAZm93ObHvJab77xEpRa+RA+pPRFmmr1+
                    m9a8vBUlPjJO2b0YQRY+4JIBPqo/BT5VHTQ+PtiWvT9Rc711AtU9cawGvmTKL72/74c9CHqnvPXH
                    /L2AMiu9uPiovSkmHzz/eDK+1zUVPtXMvb3OOtU8r+xJvcRBfz3pxR4+szL+PRvwgj2Vs+u8iJsq
                    PhGSOL6doA89pbnbupcI/TvKn806vWoiPmJYLj6G+f69AVy6vOweyb1iZJ+97fl1Pd9NUbvw3ay9
                    iJ2/PZbsILxJnSU9YySvPd9mvD0oVwG+PkkjPqoXIz4mAsa9FLhPPRs6BL4zi+U9BssRvekdPD0Y
                    1As+k46dvZz0tb11H3K9r2MwPVwXIr5mO/G9zFUpPT1DoL1GIvW91eGbveB5sr16pMk7Gxy3PZcH
                    wjwkfg49upZTvccyCb0xJpS9wN8LvSoBiT3dQ/A9Uff2PbEP6b2/yOM9sbq6Pahfqb3NWjk9iN/Y
                    Pc8U8j346Sa+PULlvVmQwj030zW+G8eJvZplV73Wxha+FQ8BPkrH6L2LoBG+jFwOPDctIr4OVsu9
                    xao3PmzBKz6vDw49VIgePhNx2LiphBU+jcacvHepsTzFgoa9N1EVPsgZfLrj2sq9uaW7ve34Oj0H
                    N4S9egMWPP0Ujj18Gb88n5tMPY7ip70YhSy+8yknPebFaTyPj969rOHhPfHIa7wlNdG9JCR0PWTx
                    ub3B3tu95o4ovmri073huBe9ueuQvRRo0D22OLo9aMrGPN30vb0fMX286JpVvSn9071yKDK9IWA6
                    PlqxJz2yqpQ9JJYaPOU+6z3yJpC99WogPNXJ2rzx0e09lJbzucSsC73kzRu+NciSPZTnqL27ygu+
                    ejXDPTFLvLzTbLC9KGqfPZL3n72uwTE+20IVvtNsvj35HLg9kvxJvM+Ozb2hfOg9bcvHPemGyT1k
                    8KG9pk6PPSXsHj5vdNq9JjStPPeker1Bldu9V3CNvQ/q17y/fHg9LDuLvc/i5L3gJNk98KOCPZj/
                    sTrIpzO9qGoAvkSgCr0ZezM9tw42vZMwBD4FMBy+CWgAPtVtCjzeCSE9PuCPvJByCb7pSDk+j/gF
                    vLTUC71uirW9sAQzvtswF77sT589jxKZvcqtjjwUuyq+asBGvX7+D77mbv09sphSvIwHBz1yxCs9
                    amyQvHLqLD6bVqG9hqUvPt2ByL3y0wA+7tFKvVt/0L2zHCi+S1ISvvklqD2DLzo+2TILvkPxOL6j
                    oug9FWMhPhXeNz51I+M9IUo5PrF0hL00F5a9XTm3vanDqb0pQae9r8yavMyI2z0ihOc9BvR0vCPl
                    Tj0yiwi+NJ3uvYa1JD4mvr68gS01vnDN8j3vSea9Ka16vSZ25T3sbgK9Df7zvPLn1j0m8Hm9PBkN
                    PtAFIj42URC9wccYvmhdaLyUhKi9NR5bvUD39728cYa9FJryvevu6D0yaCC9b9SzvXES5T2EVBi+
                    z6UvPmLdyb3gELc8TXe0ujm/B74Q9TW9j1s4PgnN7bxlCJ492aoyvr5ZDD5gUMS9xMm6vWbGlz2n
                    MSI+yMUYvjwSOb6ABDc+EWrmu/mjtz2b9pY9Uc7PvW7ZFj7ReSu+nzS9vS4oH75yuRG+7hCFPWqy
                    gD2w0Ie9IlOHveTrCT4Lvty8GMDfuyPmnLwBZNM93fevvRNUOb4LZ/S9M5CQPA54tL1f0/a8MrQw
                    PglhXb2Pyi68JOZnvaaHeb0Whxs+aWPavJKM8L3+5CS+ciHbvc1RlryQLtW9/6jpPS+zDL5ZmTE+
                    bcyYvepQMr4FFui85Mf1vUUXAT5P8KE9q5C0vdV9VT0bExe+tW4UPtkf1z0Onfw90TGMPSqUPb1P
                    3Zo9NEezPbDwIT4muSs+yMocPmSt6bx6bKQ9UNy/PV3gBb4z1P69O2fvuic8Rz2BfuO9I+IaPkkD
                    wj2d6iS+2jbMPeny9b3dPDq+9UPAPYHhLbyUbEo8vBIzPrMO273uJS8+hTwIPgxSLb4NZII9dAAP
                    vm6CIb4JLRG+z2ZrPdunGD7HlRQ9tiYWvY6Er70zbsc99PWZvbVO1r0TxYI9q/uYvOPZsz31Ejm9
                    zmzmPV55Br2tMpg98z8cPrcqkjxQU1C9MbaAPaE2Fr6yHr697F3sPKcTIT6cxjq+/wcmPi2p6Luj
                    sC++i7o+vYyk0D2K48s8TBW4PVfavL05YeI9ATe4PEW/MD4J7wq+e1BbO9+aOr4SAp09SktGu8Iw
                    oj3nPw2+3xeJPL5IIT73Zy4+Sy/qvTTgH7zAjdy8fRqSvTiMHr67Pw++vluJvA6XI74egbi9MRwj
                    vrN3Pj1ONr+9oD+Uve2RODzBFL293bAdPehuMbwrpfI9LnSyPVQrGj6P5vQ82hZLPVFbC75OJg6+
                    iS7iPG7Y9z3xbeg9v6mivK4dN72A4N+9yqayPGZElD36fii7Hb7nvcoYCz6DUKi8UAA5vd6hjr01
                    7xg6NWZTPS9PJ76AWza+9jeDvAJGHb55GTU+NKEMvgXNwr3d8tI9lxi3vBNr9T2pwpg74D/kvYdG
                    JT6Gwj+9dYfsO4qfDL50E3095NvRPWZBoD2pCv49jPzwPKhy2rzjyCc+yPJtPXp/KD5yBxs+XF6j
                    vbdlHr6xrMy9dUa9vFzW8b0LX4089Ac0vQzFEL7aQ7E9SvktvrmVir2bBlO80jUvvAKx/z0BLtW9
                    +N/SPdgZrDwS4Um9abjCPEcs8b3BYsO61LZ7OyQvvz2HnVA9rgUZPtKVDL29fA0+8z/NvXTazjz0
                    DPS9YceXPWCHGD53G2y8HvEkPg2AAr5umQc+h462vW66Mj6OSJ29H+KHPUeuD74FcP49qsAPvi/Q
                    h71GCKk8GxAzPsaz3L13Zxi8u/+VOxE9571A3E89JoJSvVHoHr6+zpE8TReUvFbbDD33wIE9s2Mv
                    vhnDcT0FjDq9XpQePvr1kr1xybW9kwbwvNnR/rycJEO9YFXlPItLAzuguXQ92zJWPaq8vT1k9CU+
                    sonMvSgVPr2MP54994dxvaewRTwvRwm++5jqvaGnvD06q9I9MeI5vpMjzzwQ7OA7JbIzPsxUA74y
                    iMs9vsLOPZxI0DsqctC99jNrPOHdWT1WHjQ+nZ3EPYBoFz1pEOI98WrXPJCaCL5SkzS+vwDxu1L4
                    Fz2QuOk9BpUavQRugL1Bdi4+k6iKPAqkRD2dGLu96wIlPRaF3r3fAMc9aHkgPRCgTb0+QwA+sROd
                    vdB7/738Pwe+H+GhvWru1blx2jM+DFcwPuM0kL0rnxM+XtCrPWxeHz5KqWg9ZTgtvV8rerxJ/bC9
                    psMlPg1bx71Nzzo8vVgFvkawZT21iJ09zrKdvch4Fb6p0BE97hg2vs93p73E4gK94KunPG9tir2h
                    tA+96k5BvHtiDT5bDxC+tR2PvNCBQz3CDr8891wBvkrvXDtS48O9gA3JPYopHL2a+N+9diIkPjd3
                    /7zEqVU7KGaZPGJfpT3IVL49Zv77vA+JlTxPA7Q9zCzFPW6CVD0uw4k9e+1rvaThkb0KKWe93+g1
                    PjLwDL2VOiM+gcMxvYVDKL7Xuho+TboqviCiAD6ZabE9
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg3NjQxMTg0cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODc2NDExODRxAWEuHgAAAAAAAACoi8i9w/D/ugJk5j1AqiW+6/2APDmEx71po7m9yd4cvltp
                    DT1Tyh4+LUB+Pe9INr7qt7m8Q0AMvbalyT12py8+Bd6pvPTlqb2Uw0S8zrgQvmubEb3H+zI+C0BZ
                    ve0fPr3yMxy86/YLPsgJvLxx8fa9/0H1vWzCAD4=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: true
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg4MjcxMjk2cQJYAwAAAGNwdXEDS5ZOdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODgyNzEyOTZxAWEulgAAAAAAAAARr628UMELvmkHObyRAxi+3TfuPe8VkT1rk5+97HGoPfku
                    6ryYUi09z9Knuxe9Kz7Lqg2+k54qvhpG2L1iNPU8yE/EPWD2LT7B8LK9GSynPedBuT0cKAq9lkbT
                    va+vmL1B7/S9TZnkvcO24L2wrSa+vmvQPcz9a7zfbDk+MHs4voTXBj6EqdK9uTYdPTGtz737tOo7
                    bx/aPecY3D1CNwg+OzH1vNaZrz34bRG+rz0KvhXb1T1M9s66Z1IEPqGoF72M3AI+ISIuPj+dnL14
                    O9I9V5eovX894z3/fBG+XbrpPeU6f70hncI97UqKvXsPyz0odRk+52imvMMi/z2BtIU8MLKdPRQd
                    HD56qmi9Q2sIvgxloL1nt4s9LHNYvZxYfz0l3fs9IYTpvDKLxD3bKYY6t8TqvaHkO7zbZbs9EP0s
                    PsVclDzuLfC9iVDLvSuimj0yJjw9vYkSvvctn714RDO+kh6YvTVn8r2PszW+UDuzPZLcGj2yLdI9
                    FDwSPosdmz3mAQ6+71caPsSoBz7Pm8C7sKfmPSo04zxt5w08J7F9vfTJTr1P6NK9AJkFvmFZED5H
                    Ijm+yHXrPFbfuL1BWzE9M1gwPvj1Br4QNNy8YTQOPAOUpr1W2B++YxQoPv2tAT5TeSK+nIUuPmxV
                    Lb721+y9JMXrPUISjb3vYjG+O7I5vZBtwT2e9M09Yyttvaxn2L1JpCO9KRoMPmvnwD1oOgk+F6u5
                    vHmN+zw1JDc+JOGqvevQ8r354kW9UwAyO93NxTsA1x29p+ltPGOh2L1ERyO703AzPttavL0=
                - 0
                - !!python/tuple
                  - 5
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzU0NDk4MjA4cQJYAwAAAGNwdXEDSwVOdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTQ0OTgyMDhxAWEuBQAAAAAAAACV2uS9c67FPXrE2D1X76g9IyvOvA==
                - 0
                - !!python/tuple
                  - 5
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 5
        training: true
    - - decision
      - !!python/object:torch.nn.modules.activation.Sigmoid
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  pas_de_temp: 1
  training: true
forcasting: false
learning_rate: 0.001
