backbone: !!python/object:__main__.Rnn_forecasting
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyNDI4NDk5MDQwcQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    ODI0Mjg0OTkwNDBxAWEuHgAAAAAAAAB0wMW+bKwyP+QkVT+8Rvq+wEVmPaD07j0c+UK/+KHEPgAA
                    gD0AJ8+7kNYFv/iBwb5sTqK+FglIv2RKsT5gZP6+eidlPzCumT302Ry/OkVAP+6KNL+sOHk/0hI3
                    v6DE/z4EKSe/XAugvvx/DT9o8Qa/yhhUP5iDHb4=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyNDEwNDk4MzA0cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    ODI0MTA0OTgzMDRxAWEuHgAAAAAAAACS+D0/6PBfvnRotT5Gi1y/PK0dPxZjNT9kITm/ZGVSvxKZ
                    Mz9QyB0/gLInPCaRHj+0v9Y+lHHPPgj6Qb7qR38/mJ+RvjLMTL8cAq6+NCBrv0hAub7AlyM/Wjxi
                    vxBO5r6ivR+/MPVXPrCuMz4QAjg+ujxQP/SJxr4=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: true
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyNDYxMDY1NjAwcQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    MDgyNDYxMDY1NjAwcQFhLoQDAAAAAAAAlrkiPOlQ9bx28Us8CCh7vag8/LxBw7u9DDETvj8lEr7b
                    5KI7JTDKvMrpH76ftSc+h/8HPvq6M77F9+e9WAwfPklSlbtg8xM+vr0GPTq+9j1T0YC9Gg8Ivlj/
                    H75LL+M9YVIXvgz2zj0ciuM9bJsyvbxOcDrSpTE+bVnIPZjsOb6M2Va9yYd8PcOlSD2VOiO+KsTb
                    vTAT7r0CH8M9zjBbPX5TqTzxT5A9vGAivshrzj2WAyC+0t0cvrybZb3nqLq9UCYtPgCaDL2Cxwi+
                    o0C1PCiiHb7Vuba8tIDTvHiVJ75ZBgk+rbYrvmFyK7wVHbq9s4nYvcQZnr12MEW91VI0PqyyJz5U
                    vcg978I5viuQ2L1yGxg9iv33vW6Oib0qS5u6h3dsvcydfb0nnMc9nCvPuxHS4z05FM29TwzovdLq
                    qD13Yo09LVLxvBOkfb2VVG09QYbfvXh0zz0G4yu+R2V8vU8EgTzIlck9MYXDvYQxGj5hteY9KNAw
                    O51iST3lvaC9c6DUPTM1FLyIadE9u/xGPQyYIL6XSSs+3QYBPW7sJj6JvSG+TlsUPgfJLb5OYzI9
                    FeGuPWNwP7sB6fy8EREqvp+owz1gxds8JGguvmwzlr14MN08VV+WPU/IFr5DM9E9CC38vQHVAj3Q
                    Udq9zbFPvWVcXr1RuEg8nReuvRP0GrySg0M9R9ioPWh2NL6wzsI9kaOnPQfXFL1AGwW+eDAyPrRu
                    GT4f4xQ+yyCCPTxvKD4LDKS9bkFMvLxHJj5G+WO9MVUzPWh3Nb4RCMW99ncVPmkxqr26/7c8opW/
                    PNdLCr4SlTe+MYKSvckctj357+I8monsvOqbLb7iGWo87BUKvmHxOr7HZ689L53zPXItpL2/PSa9
                    DBTFvIWnLL378kQ9htEHvncQ1701eug8XxLMvWhZij1nJTg+XgTIPSIqwz3RpPO7kDIbvWPqET6s
                    Jhk+hpVrPRL76z3/OpE9sXqcvCEE171g7Rc+8QuLvAgB2L29KwE+2DugPX2eND35a7y9eQHsPclQ
                    0r0vbtS8uroHvuMXWL0El469lcApvACbKzvAq/i92UpKPUnpu73oshK+kJDXPS18Qz2/fAy+NOuG
                    uyGKlL3ey5u9tjHRvSttXr0rwjg+nA7UvXKWAL4Ysaw9ee7SPQTCzz2ejBu9KhqpPSKEqzxPsJe9
                    N4MyvqhTzb3kJyW+UUU4vsPlML4g7B++AhoQvmTjVb2eAvu9zep3O7BrC753EDc+hsuJPHcEIT5O
                    cRa+IhE8vTNRDz71W9Y83Disvc2zjb3WMzY+ZU+XvK/nWjzSBR0+Or1CPXB4FL6t09w9Ek0rvl4Q
                    QL22BAW9P+nLPGOI3704YiW+4NnLPZUmNr5p6TY+j5UDvuMSLD7SvLw9z6AkPsrkBb4E5qG94sag
                    vF623T1+17q9ndMCvdnq3j29Bx0+0DAsPjRY0rxB3m69UysQPYgGLr7vy+g9pkajvYOGIr5HZIa7
                    tQYwPbEZ+TtAejW+ODhFPVcXnb2px7+8VNk6PhHoBD2SUBS+5HHFvc80hj3O17u9bVIgPqFB1b2v
                    UcC6jPGfOj3tWb3YQx09W+8Evv9jyjxrhs+9cZcBPZHvMT7qNRo+lBb1vVj/+D0Q3SI+MfooPu4G
                    +z2ELMa91NYxvr4eDj1gdD09W1qcPbW59T2Igoc9vfYbvjCvrzytg9m9rVkQvgXLqDzWfGU9AVPf
                    PQgMK741uCY9wHMTPhByBr4Bzji+u/Khvd/YGrwZUqG8MkecPWvV3j10cQg8ZV7qPcIOMb4dPjm9
                    Zue3PPOHHb6FQmC9laLsverZ8D0Ux8C9sjrMvWhc+z0JECY8ix8MPry8lL1qYPi96jLTvY9C7z06
                    zxa9UOyjvX1z/b0hyiM+NyAxvGq6nT0Omt09ZdwCvmDCrb18NiE9u+XrvXTBnL3n6d+9eIQKPsTH
                    pDtCSAs+dAggPgOaEj6/V+S95yXIvWXKjb3XMLS9m4MXvmt4HT6YMBo+nwhEPWUxFrv18uC8HNqt
                    u1FmKD6EXVg9ZK/jvWcHS7y7B4E8qlcBPmtB4b0PHAI+u2wrPllZyb1uXyc+2adYPHpSPrvLsKS9
                    vTclvgwglr1ZPBa9hIR0PYeJAz4fQRA+HIjJPWoWvD1qpgu+TQI4vsvh+TutP589Gyqbvfua5D1N
                    qIc8ENNIOxFT1j25WXo9XwBOvMFo2z0vL5e9xDcEPpBr7b12wZG8Y3vpPXBNCb4vZru9a9cAPq4Y
                    ej0gZf48y10NvsBsHT7Zg6E96dFEvfKtGT7Itg++XfQEvvdAcb3LqyQ+/b0BvZElhrxs/UW8OaGb
                    vV6JeLwUdw++WitevUXGGb5mnes6TxyePXltAb6vhCg9+W4NPuWc3T3xrEE8Ob6Ou20rLD7oYea9
                    NI3AO2XqIDzAl4k9/Kj0vBz2pbsmSoq9U9InPrVGWb0B7Dk+N1lOPV/kEr0TrlC9mbfyPWP28Lxc
                    Wem9JdkvvvF9bz0cZmo8kEEcvpc2VDwBwrO74m/vPRsK/L2TKyQ8y5eAvZwDOj4bX8A8takOvh+b
                    1D3QODW+tocbvfCriT1fQi0+S98CviPnN77vNsm9TQAEPkxqEjzUpQk+7RIFPSHljL1SGyU+1yVi
                    vUrcTb1QkxM+U7ujvWpBOj0YHB89Hs0PPlUuarwvspG94jnEvV/OwD2hbDU+1dCmOa4pbz1v59q9
                    sV4Ovkc3GT0sveI9mIm0vc/u/j1tTg08v3EKvvmAIz6wGjc+2QvDuZsowzyFcA++bB3APTFM3jwO
                    Uyu+g+UGvl57ML5hK8c9G1mevcFaLz7xwL29mbkZvv6M+r3c+d29AD+tvXmxUD0BEt09IBHMPYUE
                    cL0VFZk95RWBvY4+EL7b6Ri+Jv36Pe2f/z3X26m9msx4PSdQfr3g6fo95VtxPcYtoL3F4N69whDP
                    vXQl9z3Br7E9EtIBvW7/cr35C3Q8XocJvo8+MD4AhV26n+nrPRucGb6Gogm+m46/Pb7aaz2ZxOE8
                    x0hlvQ+b/b2sbSM9MkjCPTqPkL2pbgy+5kbbvJ79Db5y5jO+PEo0vvBzmTuhW+i9u3bMvar0o7xm
                    kwk+THE3PhUi/b03ZZQ9dpMHPsEnMT6+hzc+L8erO42d7L3yZga+W5aZvase/b0tXoo95BPQPPFr
                    9b1kqFu9R0KjPcYt/zydop48PEY5voVfIL6FTo26JoGDPRSuY7s5C729ds2zPTN3FD0lVRO+C2b1
                    PDF92D1I7zk6JkP8PSjB2L1DqBo+MpwQvkj2A77Y3Hk93CXMvdtEED5hvwo+81UQvmIk/z0u6gA9
                    4atTve5Jb71rFPS8K5UbvgOmLz0H94C87Ma6PYgcMrzRkhc+OZ4ivqvUGL2l9Me9Tj0BPi7E3z3C
                    1cG99HQ/vUmhkr0Cd/E8iGuLvcwnDD4Vm3I9UVkMvimf6T25WSw9AvAKPq6S1b1PTQa+4UiMPbUF
                    /r08fxO+YdsrvV149719kSK+LJ0Ovq2VJryu99297N4cPjcWF76ZkH493dx/PSainr3srhu+Nei5
                    vGohGT5x7eo9pzYgva4LjL12Dxu8ZSEIvCaZoz0FkAq9oFjhvS+GIL7EJR++mq8rvntuTD1hzSA+
                    lmYqPcsDFr4a5hi+i26vPVsfF76J69s8pUUAvrymHr6PCoc9EA6Lvana3z3Zq5G9PZcHvqcXyL3E
                    5c+96yOTvblR6DuINrC9qpUZPndWwL2OlQW+ngUXPk8SD76JIty94jPhvYYuIT5k2zK907+hPE7D
                    Fb4A3Yi9wqQFvZ7cLT0LuAI9Jy9tvQU9Gz7SZdA9mso0vf/sJz6bixm9IXxXvbIL071XgGm9Yy9F
                    vJmS5jsCWP28P5aiPVGfB743aAK+qPVRPBldvbuZhqs8rAzcvECaCT5cgS8+ElhtvfJBP71isjE+
                    WdR3PC1BFb7O+Sg+Kt7uPaY7f7olBlw9pnkRvtSvIL51wCG+hziePb6bGz5sA0w9xEwrPT/SP7si
                    J9K70KHZvY+Ftb2d+R++nm7GvKF2VL0sEwy+r2YzvoHpjj3Q8YQ9A12tvdtJ7TwBa0c9/a0rO/Tm
                    ibz7pJw921Drvdii7z3rfC8+kubDu/BWU72UeLc8br9tvZA4xTwScRQ+skrhvUsGrr0InoY9s2gH
                    vSuv4r3HTxK++Fi6PfvWV7w+BTe+9moIvpxNG75+iQ4+6W6XPf0d0L372/Q9Tip/vJZnHj68lQu+
                    akUYO0e7JL4iA6Q9sxSmPQpJCT7z4ZG9SpiUPD9TJb5OVma9/cgvPhm9Gr7UQZu9Xf5/PP3veT38
                    Vik9t6DYPZZqgj2U7BY+auOTPby/Or5TmhO+5y0DvmRFDb7Qccy78DqDPfpnFL5d2zc+jFu9vNEK
                    C74DeIC9JJq1PHYeB75Ucum9NWnIPUCE5D19+wQ91/IePntoKL6wV+s9euMTPg6Ghrx17Dg+fXMe
                    PgL8170NkJC9UaIWPUbhTD1e0/u9nRErvYvIAb4rDFw73jyHPT7KLT6lAyM+4c/gvcywUrrvIAW+
                    uwA2PtegCb72FoM7sv+fPWAu+73VuJQ9i/0Gvg9gBj4RGcS9HgzsPYa8Nb7L/qm8a7ISvkajPb24
                    7OW9Rn63PTLji7y4uhU9yMEFPqI6qjsHN/s7wzozPpVrDb4hQCY+LF3UvaYXGz5Q2ws+qfZqvfVk
                    Hj616N+9AEA2vp/AGT7CPEC9ktE3virUij3CXCq+jKAkvmEaCD5zzX29GDElvjKe1j1Ezww+TfkK
                    Pq1Err3VzuE9KN0Avqik5L2xETI98easPXrWiTr3qzq+
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyNDY1MTM4ODE2cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    ODI0NjUxMzg4MTZxAWEuHgAAAAAAAACxXAi+TUnaPXDMLb4Yr2q9GO3avTInUD3CwiW9akQuPhyK
                    xz0iI6m9kNQEvvszNT4VcRu+wFpFvdhn0T0COms93GqXPXpy7b32H308t6gCPjzqKL4tdcW8lVK/
                    PT3q4D2FGZa8YaKRuph1Rz2kBV89I2YQPojH5T0=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: true
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyNDYxNTE1MjY0cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    ODI0NjE1MTUyNjRxAWEuHgAAAAAAAACF4CU9FLoovste270g7hE9nwrIvQaiqb0gfxE+1CMwva9n
                    GT72ER+90bivOwxeMDz0I++9otLJvW5RcL2yd+e9lKOxuj2ArbwxXCW+YlURvgkVNb6F2qm97clP
                    PQKk6L1s7Aa+3nQOPofRKr6UZ4e9fDIBvs2E1L0=
                - 0
                - !!python/tuple
                  - 1
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyNDYxMjIwMTI4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQw
                    ODI0NjEyMjAxMjhxAWEuAQAAAAAAAAA+hyi+
                - 0
                - !!python/tuple
                  - 1
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 1
        training: true
    - - decision
      - !!python/object:torch.nn.modules.activation.Sigmoid
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  pas_de_temp: 1
  training: true
forcasting: true
learning_rate: 0.001
