backbone: !!python/object:__main__.Rnn_classifier
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0Nzg1Nzk1NTcyNzUycQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ3
                    ODU3OTU1NzI3NTJxAWEuHgAAAAAAAADUbTY/3GepPly7ET8g7kA/wBxBv1ScyT7kwlC/GE6PPiiK
                    ET78Vre+pGCYvpi5cr7AgrW8ANz2vDB8/T3QhJa+eJ4yvhLpKr+YMle/6PBmP+oAFr/e+hi/yP2w
                    vpwXO7+4M2W+7idpPzxMM7+Ij20/Rqwbv2B1wD4=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0Nzg1NzkzNjc1NDI0cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ3
                    ODU3OTM2NzU0MjRxAWEuHgAAAAAAAABIcBS/IJ7gPipSVD/AVms+VEwSv/JKVb9gva8+srJavyxn
                    wj5ewDy/TLAOv/hP2T4gNdw+4JbrvWAoND6wbry+oOPnPpTSjr4kHVo/anArP5jQRT9g7Ee9YNb9
                    vrAIFL88XVA/uGg/P6jnoL4EQGu/pnJhv2ABcL4=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: true
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0Nzg1Nzk0MDU4NDk2cQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    Nzg1Nzk0MDU4NDk2cQFhLoQDAAAAAAAALqWBPSJvEL4nBxO+3SgdPrp4BL6kVe09pxWdPQC1fr1k
                    WGI8asxiu9TXUT11+3W9Oow6PYozE70+ksw9w45sPJJ6uTwEP448NBcyPp+jqT2v6DG8JVMLPRY6
                    BL5EENK9K6WvPUlgTDyEjIc9YM2qPNlOML0mTja+OrkkPcYnCr5WIr49C5UdvQ6l6L0fb4a9Bewx
                    PnGMwboEsku8WyoJPvsnJb3g/Zm9QZGIPS0w2j2IPto9QA85vt+t+71GczK+/j4AvVEAeTuoTzQ+
                    tIo1PkQFYD298Do+Lb0avpLEC73DNDe+qO81PmQO1z2L5xa+n18HPoeoQrvOQLw9F9cEPEvjAj2c
                    rwi+hnJAPTcglbwe1z484wAlvva2Oj6q7Du82Ndrvbl72b2UwDq+hvLLPUxLMT6gAum9AAfjvSKY
                    AzzWfze9UBytPRQmHz4nDhw9a70HPu7Dizzv3TA+Lm1lPRDq6j1F9RK+ST9UvcfoKzyiORO9/0UN
                    vitOJT6BJAK+Ajs0vVZ/CD4zH7Q96VYnvcIU1730iFq9lHiCvYz+RzxAyNS9jkLnvYicFj5K05I9
                    3STqvT3Cyr2T9lM9LGIVvG/I97xXiBw9nkVsvUDpwry9Dnm9+AELvvoHGj55pTa++a3KPdntpT0B
                    BIK62URSvT7qB75xMku9FIcGPg7vHr4WaDI+3ryEPY9QQbwb+wm9eg6WPFJnFj3dIKI8nYOmvacq
                    FD1IySC9XRnBvQ46Bb4v6CC9Eioxvmgb+r0MASE+uorYvDjgob3kAZ29TCeMvaB3gD36ras93QSD
                    PQy9LjxEIOc9rc3rvRu0eb08Q4o93VM5PhyxQjzmbj09Z78rven9kz3nK+A9bznpvXZ8Gj7xXKK9
                    CtOSvRb1I74xB5g9aHjFvazX9T02s7w9/3j5PByBiL0YWTY9vVYXPp6uhTsD4aK99aajPYME7j23
                    /fi9Eh0DvmUlKL77fdU9Q5+bPUxhOj652w89zPm0PDOOJb1aBRg9h62VvDbNob0nfjW+UpdevLpG
                    Dj69jf+9urouPshFFL4zuQy+WQIMviPQKL7mQ8C8e7QdvpGHQD0aG5s96empvbK7yL1y6k+9Gu+Q
                    Pf8bVbzxNwA9bTPBvV4Enj1WJmA8idM7Pb90Ij43hvC96JWOvXphjrtpuzU+j0AovrDeJT7H7ws+
                    AIIKvkk57bprKr89d48WPer84j2sjWM8nJ21uwATTb0Yq8E9rY0uvl1tlD1XnMy9IkO0vXMnCrwf
                    szk+Ph7KPRbMxr0oFRs+UOPIu+/I+r1I7b89TLEYPioBvj2EHDe9G4bDvdaqgD1/sek9ausjvoud
                    +DvQi1w9YNX/vRC8dzymOog9GcfXvP3uHD5o2he+OrC9vQfLJL17BBO+RF0yvvHMQ72YNRM9jj0y
                    PTDIx70kxP29KwETPlJ2ej2tSA0+m4ZDvewL3T3LnSq9lTPuvTvKlr1fuhG+BD+nvQ9duL371zm9
                    tZGOPX1Her0Uudk9qSFMPDRvdD2S1SK+EvLMPRIUAD7Vr5+99gOVO+hMqD27LaE9S+z5vTAH3j0R
                    cjq+Bf2BvIK3m708I5q97F/ivbbm2bxLUK88oUgpvatN+L0PpRC+fP/5vY1hC754xIW9Ritqva1F
                    270brK89F/NmPFsJBrs3KG09tPekvbRxNbxN3fM9D4qCvLi4D75i6yI9xRq+PaqtL74gFWM9QIIy
                    Pqwh873TicO8id60PZAS7z1XSlM9H5CtvfmEzT2vTAW+cYiOPZrREzzNxAc+SD8svqYZ+Tw3FVg9
                    MjeKPVPkPL3iswG+RohcvczyXb0+G5m9hHO8vSokqj0hJI48mw0UvgKtNjzVIzs8PcquPALV6bxC
                    fBW9Ox4RvpkKyL0pSis+As42PVnhajtuqNG98dJMve5BKD2h3Js8eblzPfjStb1e3R0+KHcnPqJe
                    nD1r6v88zaz5vOG6NT6JCpm9Zqs6vrItIb01tKu9jgUFvGaT7T03gci9q3gsvVDqI75VOi0+yUXL
                    PeSQzzwih6Q7vEUFPlUpvz2HHym9j2b5vYRUL76W3H+8bEz4PdU5JD7+RI69RyIOvvXigTuLRgY+
                    AtYBvmGPbL1twwc+hKaQvUvYFr4PA7+9yMopPdneI73ItmK8zB5FvdOTHL7IzDo+VkuNvfxY5r2v
                    Tw8+Hx/KPfuD+D0IxM28VwQ6Pq4gl71BPLy9OtcovcmHDLxagT49hhC7PaVsh7llVzc+siITPYy9
                    Wz2LI6E6LM8avcU/iL3ahqE9Lvu/PcShDr4D5QS9yqBsvc1h170LyvQ9A3IuvbPQRL1oXRc+fPIH
                    Pn08MD7pX8I8Zqofvv0c0T333yC+K0sVvN9Wxj2MPvs9PsDDPV+52Dwx5l69D2F5PUj96jzWPI88
                    gSSCvSQFCD58HhC+jUYKPiZYFr6TfrK97/snvSq26b1K+ba9J6vCve4F5L1qiNM9wORvPfuAsbyS
                    IgQ+kkGqO/DdHb0wP1I9kkq3vBVEeL2M1CE8MBzmPUT5KD6qnzO+243rPbQ4p73ZJgQ+jiboPYH7
                    uj1FPCU9Fq9dvTx6nLvrGqI9pSApPHk0w7wSsCa+prvhu8fetDy6QgY+L0WJPS+Tx70rBAk+1Kp9
                    vSa8Mr4UzRi+iyTjPchs2D3LtSA+hXwJvkWAHj3q5Ns9WSgUPmVvLT0gDui8hh2uPAb/LL4M3Ik8
                    R4YfPrnVF709rTI+f9tPPZWFZD0WP+S8tNdxvf/DID5wxbI9MVmcu8M5SbwQhNg8DBc2Ptqsmz2V
                    7DS+9AcuPnXVWbqNnKS9WOiEPFMnCb74DnY9ERMWvsSuHT0Phhm+IeeqPUKuNr6mKJE8i98pPhrl
                    cT2n7eQ9vgM7PaAfHT4DFYe8q7z7PFnQDj6sFom9R0eHvVbIIr49x/U9uO4cPOVZLb2WkRm9V5vx
                    vejg6L3zfXw9QPOHvWYzgL1ddbw8BtQwvlhcL7zewAa9IMHZPQTVkD2CEwS9wVIjPvI1KDxKRhs+
                    pti7vdMm9D1VCNG9GQRYPZwtKT0wtuY9Yt8cPc8TMD7P54g9F2mBPFvNuT1u9CY+k86SPGVSIb7Z
                    Trq9q2bKPbiAQL1k3BK+YFUqPms8Kj6emvo9iR8xPvZsIz5M6iy+i5GXvfWIHD2tq+i9sgcuvqy+
                    mrytA+W8oQkaPt6Vur1Mk649LT1NPRoRLL48WgG9pz+7vfUABjzbSAI+DD4ovh0Sxz2emyK+HXzT
                    PVTtwLxUTr89x+DEPXhomL3I7hE+pC8NPqpAUzzrtZI9w43uPfvPiL3z1YG9XwRsOrZHvL0UTJg8
                    OyTtvXuwsLyln2o9r/AwvqHED714W9M9Ymzbvfd4Hj3wRgi+xkNmPTNS7j2xzq+9eNcMPtepfr0D
                    K+09QdvZPLh9Ij63BeE9ZTkXO8X1rTwnSjC+64QqvhZiaD2WNBw9Oa84vh7HCT0rBcW8aGgWvoSG
                    MjzOVjw9J8b7vZ9j7T2BVA2++YiMvMWzlT3ryIy98KZaPccgKb7/Goy9/XgAvqQgQ72HgAo+D6wL
                    u911Jz4oqek9WHz6vd/OhDwdahO+ax4Fvkd/Cz4GVbe8fX9yPd51Db6o2fi8vogLvnOyCDzV5Am+
                    u4/Bu2ou3D2Pmsi8rCU0vsDW+j1RaxC9DuwCvXWsLD77IgY+OO8DPnPuOL6O2Cm+e1aTvW5QZL0u
                    qhM+qRctvq72Ij14/ak7f3MUPl29Uz0YURO+Qto0PZs+Hr4dMJY9tvUJPr59Ar7ndRa+x82APfew
                    N766Mxi9gS2lPbjhCz7TQeo8TuAtvkvJUTzpPjg+DR0EPgzD5b0nhTm+c/v+PRPJMD6qYh2+oeo3
                    vsCanb1h+8Q9wTwqvdavOT5UN+E8VoIbvmf36b3mGoq9xXPAvUaqzDz16GY9dDFlvZrn6jxvWBe9
                    cdU4vqND5jyZ0r48le0ovtlIjb0lHSk+moSzPbU/IL4eVCW9RwOnvfRB3T1kQxI+RNMOPsVOJj3j
                    t2k9FE5fPcfrFL7+8DA+reOvPFnRpzuNWCe9Z+bOPRzk1T09KKC9LnEYPr6OdL0ovh++ylstvcA+
                    m7luDjC+B1rdPVt4hD3Yeu69+vIOvs923r0P1xC9sVEpPpiOTjwoAX+9gowRPh2sYz3yW5e8WSQA
                    PrONBD7jnzY+UxH+O7VE7T3Uh1g9TNj7PU33nLy4qPO9k98/vXZCX70LUAU8jpe5PZYwpb3hcDY+
                    1t7YPaiaMj7d6Ps9QB3Hvb/wMr4NRQo9w0PmvV5usb3cC5m9kAnXvRYxNb5XiDG+3yscPtkXGb7u
                    Cre9ShHfPflT4T0KXOG9atQ2Por6Az6+MGO82XMbPmZiCr2pG8K9v+8ZvT59+b0rUyk+eVUGvkjZ
                    j71EbDu9bMHZPWClVj2iIh0+z1qpvZe0cD0KBnG9gAUiPpFEHD5Mfeq7m20XPuA7rb2NKNI85/4k
                    O3eRzD0jcSE+FoalPR5Wpr3DF2c98SnEvczk6D1Fflo9TzolvR7INT7WnkQ90bnpvTV4Mz7wHsM9
                    bS8dvu+JPj2Usmu9X/c9POR5Fz5EuOo8/GooPWpLyT0kqBu+TfecPQv5G70KViE+SkG9vX4eFr7Y
                    8wk+7032vewWFb4XTjS+EJ2cPYXq0bsWo7Q9lTWQvdslHb6Y3vc9ChdNvdhAwL2MAQg+iqU0vmVC
                    qD1uYaq9KKJyPWtJLT0izWy9MZcBOyPPhD2egbi9dXvpvV9oKD4PPDy9rJFlPRwpDr45qPi8qh2P
                    vb/kjjz96gc+cp3oPB4NGrwQnZ+8SqDlPRCTBz5NByK+
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0Nzg1Nzk0MzE3MjE2cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ3
                    ODU3OTQzMTcyMTZxAWEuHgAAAAAAAAAZAzY9znz7PQuE4DybrSC+TgzxvczAKr6XTso9OOfpOxL5
                    ID5fQTi+sYcdvU/xKL5KEjY+sIoGvn/43jwssYQ9lUq/vSxGOT4jgR2+Geg3PihHhT3AlAu+27of
                    PsbKbb3UUKC9o1G8PYMi/73mAZm9znOkPSREEb4=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: true
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0Nzg1ODAzNjE0MTkycQJYAwAAAGNwdXEDS5ZOdHEEUS6AAl1xAFgOAAAAOTQ3
                    ODU4MDM2MTQxOTJxAWEulgAAAAAAAAC6WYC98iJOvU0aKr54ioK9dK/au4VWtL3hbyi+LItnPZqR
                    V7wHffq9BjSRPfFwpL02rwi9fhYqvpdJCr2uG+S9XbWXvRrmjb3FafQ8lbzyveBkHj4rABU+jGE9
                    PeGPjTyARvs8y7gmvrhawzhugTo9If72vUS5+j1fwys+m7CQPY1RVjydBPg9xt+9PUb/GDnpVgG+
                    YAonPutVjz3Y4XC9pwzWPehoGT50phM+YoYTvRNPib3rlPE9YtszvhkKfb3TppA9+RaRPckTJz4E
                    cS++BXU3PKY63T2NA469H6oPPq8CzTwcPZU7Hqr7PX3zDj1CXeE74LOdvWjH5T3988m8MILwPbLW
                    K75Epoy99HulPY9zMTxK9R++k1w3PYB8ub3MXQi+3rmyPERxYr0g4ks9qNKtvfDHubzyyJi9P2Ah
                    vjpJJT5jqzE+ioWlvU34VDtSCpm8cz5TPZmkE711JDS9SzWjPd8DBz0/YNY9NuHEvSOozD2G6RC8
                    xD+fPCH1Br4J2qg8A3oDvrgqrD2k6co7EfxlPB0frD2xhx4+oa17veNQjz1sime9J3MsPiL+7Lz6
                    ISS+IIQ3vafn071z28e9PNkuPT717z2dgaE82OokPkobID0ZINq9wt8/vEO53T3uDgA+JFaKvZjx
                    Az0C7oY9wMOzPco9+j2CBiy+uhsLvrG0xr16jpE7aCRAuiTfsb2uTjO+e2NGvayQ+Dwbdjc+ZoTT
                    PD1Kybz2KNI7MAABPhEJx71QGJ09lryavZT3M74GQyg+amACPuglLb2S2os9FYkzPtH9h70=
                - 0
                - !!python/tuple
                  - 5
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0Nzg1ODAzNzg2MjQwcQJYAwAAAGNwdXEDSwVOdHEEUS6AAl1xAFgOAAAAOTQ3
                    ODU4MDM3ODYyNDBxAWEuBQAAAAAAAACynDI+OGXmPRSHM76vjeq8u3d9PQ==
                - 0
                - !!python/tuple
                  - 5
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 5
        training: true
    - - decision
      - !!python/object:torch.nn.modules.activation.Softmax
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        dim: 1
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  training: true
learning_rate: 0.001
