backbone: !!python/object:__main__.Rnn_forecasting
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg4NjQ1NDU2cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODg2NDU0NTZxAWEuHgAAAAAAAAAApvU7AKpNvB72Aj++wTM/CF8uv6Sx7L6ESYA+YEOSvh4u
                    UT8AANY46AigvkDkGz5cD2g/gKS6PGS+DD8mXy4/LFCDPsD4nb20t1A/JFNovyA6Zz3Kb2o/WF/8
                    PnheWj4Qq6G+rOf4PmB1Qz9I9fW+SHqHvg4wcT8=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg3NDcxNDU2cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODc0NzE0NTZxAWEuHgAAAAAAAAD4p9A+DN0bP+DpdD/cB9I+LPkuvwRa1z4g41Q+GkEMv6C+
                    Fz461lm/dD8rP9KJIr/q43M/YCBuv1QqND/Sogy/+CxLv/Ag+D3IS9E+bMIrv+Ce0b5Qdmu+0Eam
                    vfiUQT/w+bw+XGNpP9qPJz+as02/iNQ5v5qRJD8=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: true
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzUzMzg1MDg4cQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    ODQzMzUzMzg1MDg4cQFhLoQDAAAAAAAA1Y05Ppzffr1iOzc+TK4GvhLUrL2GvUK9INP+PECyu727
                    L7c8ZMBtvTIhaT0+nds9z4xdvegtXr1dJA++46ooPrdw773klBQ+gspsPaRf0rz3qdu9C9wVvoe8
                    L76Ts5s9MxqXPcbOI769r0K9ChGnvW/EOD6E6Es8KLUIvizjHL4b7Qc+UZ+wvKe6EL6z/Ec9lfAr
                    PVS8uL2HRg4+/JoAvWzfNr06+iA+z/sevj0cITtFmgo+fHb1PbM7vr1r5yw+k3fova1y2j2xdbS9
                    jZl1vXYoob2NIxI9N8fVPfRKLz5IeKy8IAoZvpuifj0weo09rqAjPthdn7vum9c9pBd2vTp9I74+
                    3Ci+FMYevbdrTz0CaRU+ZQcZvsHcmz1WrII9SkCwO4pCLr4NnhQ+xu0Avm6vyT3ZNt09D6XMPcrg
                    L75iSMo8eJr6PdUqa72hXWk9GZghPuklNz7u1Tm+ZqwcvqS+MD4vXiO+hWEjvntmBz4+hLQ9EYMw
                    PrA6rb2yuhU+N5MTvuo44Lz2aBo+B/xyPSSluzzN9wU+qGa1PeldMr6jVxQ+Rf7NvXhJcj0X0S8+
                    dnAWvlw+AD41i2C99jopPSZpPbxAfwU+3tlCPUEGFL1gzTI+xIFlPY9qXzyFWY085F9HvDMgl7z2
                    uje+h8wNvg/kir0Un309a6aHvYKPnDy/2rA8BkrQPa/rqr2G8yW+T8eyPfLgGr6lsfc93o4mvnZv
                    J77pDhU+Zur8vYj1Nj6Chva85yOyvZfSOL50Gji+NMyAPUjAZz0XWx4+Fb5XvWnC47388RY+vi2P
                    vWluQTwkfDI+NyKWPeJ9EL6Bgco9t1qsPc71ILxruBM+AYjsO+4Htz23EdK9zC28PV+gAD2IMxG+
                    fsIJvsGOeLoN3pK9C/GGu/sV/72HsqA7t9yPPeDC+r0BrYs9tf6dvM/0G76/3y8+KnUcvnp12z0g
                    IbS6IrUPvcbBj72V3Ra+vZAmPrP5sj1TQay92BCiverOgr3TO3I9GK8WPiPHebw8XSq+vYcRPkWu
                    Q71PCAU+lNEdvunSJz5p7zG+R/ENPtW3eL1CPwc+4KOnvc/YRj04HsM9en/nPViAOb3sUtC9/rnE
                    O42yWL0DFk29igcYPvJoED1Slwu+lGScvbLUI74aSh8+Ha4LvUv32j157RE+la4fvsOZjT252Ks9
                    XSU4vbhbor0Nhc09SHh3PZqKEr7fQvu9au1+vLHte73bnWs9VNHnvffteDxergS+lFZYPR2Lkj1y
                    wDQ92OojPnp+CTz9IYi8c0yPvaEauTzvMZ+9GAu4PbcqZrytN/C9jjBYPUKLID49rbM88KslvvRw
                    wT3x8u297X8cPl/13L33R909tCmzvbhlfj2JWAk+SP44OuBYyz1ecGM8N5wCPjAMSb2OtQG+KveV
                    vZnZTb07rR6+IejTvM1hC750WQW+PXQavnhcIj6NVdi8MoiLvQYEMT67usq9sHPmvXNRz7xT5wI+
                    YNn9PVWA6r2hW9A9S67Rvas27zyLaqy89YPpvfVR/L3a0r89XKyMvbucJL6c4uk8Dm30vdTcHD10
                    XUE9tswnPnNU4Tz5+io+fE6UPWv+Hz1s+Ca+ZJEXPkvvCj60iym+j3fyvSgpEL0xiRw+t3UCvvfz
                    Jj47s4a9X+imvT6CJL4L/x6+2QUQvv11AT4ZbkC9cBoJPvz4aL37NsO9fpdtOwL2NDv4bJ088SXb
                    PWTlN734Agc+2OZwPTCaLD5po868PR82PF2khrwyzya+XJcSvlAsPL1Psdm8EKNzvZW9KD4p5RQ+
                    3nnXO/69OL4SdxG+nCSuPcwOGD6jQr493t7YvfdwCTvZ1RG+YgnGvHA28j2ldg89eq32vWTStj1v
                    igA+ZEjsPcjSyT1FuQ4+BvjgvKJpvLyl1ty9suS3vfW2qD2TrBQ+385NPVTWZL39tRw+WtH9vU+Q
                    KL6Biwm+lMAPPrPLhL2mATI9JOthvZcDxz1Bcs+9hBqhPZOP6b2gl9M9QTUuPtajJb0YMpe9X1UY
                    vgYIB73itcc6QuxIva+rhL2cH+K9q6QFvl6mzz2iAow9tAMvu0bDJD73bBA+omIMPR/xKD7Vg9s8
                    GmUMPi5lGT7yjcS9GcaPPS0D/z2T87A78FzWPRfioLzGaB6+T7YuPmofkb2nVhc9dbQtPj+/4j0S
                    1tE9GgEWvp2Nw7xEgga+cE5lPKt1ojy2UQw+OvtAvUe66rzH7lW7Auc5PvdMwb2xjwg+iT8kviQg
                    cj3bYMK9nbmuPSgSA75Maua9EJ5oPcpCJrsbU5g7gzuyvSH3BD0Sh/M9ZiEHvpEsub3hy5u9lywB
                    vafreT0bznC9q4QOProbEL4qzXk9IcEZvr0RHb4ccTC+iCKxPfgtJL0i5QG+zFI5vkT8xzzzyzG9
                    1ZMCviO4s70Mtuu7J6fVvY1QGDxySSA+7LkkvpYuCj5R4ue9NZ8cvMtfAr3KKPW9GulUvQENxzxB
                    1g4+339lPewCLz5Id7E9/2Ykvv5DoL1GXPw90qgevOhIij0tsGY6Hh8dPvI+kr3TJwI+9pnjvfll
                    Dj0IDk+7zkfIPBUJCz6TXPY92qyJvHbDNT7oiiM85wndPY036j3jsJM9BFzlvc9CrL1O5tO9t+mz
                    PTQe/b0QMaS97sidvT5HCb5jsx69NQoSvuuYA74Yany9JBvcvEAgXLsiDgg8plwEvi5UGz7BbRO+
                    7okEvklZob0HQzA+eWkxPTLMLD1XvBC+5piSvBXkMT40Wxi+njUVPljy5b2/EA2+AuM5Po4Nm70A
                    IyC9rmMtPjDYA74lYc29xc8ovjc+bT1DbRg9Lyp6PHmiB74c6Ck7a0wWvtapbr2WDRM97S5RPYPn
                    zz3g8Y09DmiCOpAUG76JAZk9JltdPWokvD1YHDK+6yycvPmjMj6ikmK8mmn4PF2iHr3F7cm9m/Z/
                    PWRGyzveaKk9QkknPrm5pT0F5xo++28WPlAyUL2RUTO+sPegPdtZpLog2Ym976CuPLWwID6F9LM9
                    uiXGvBmOzL3Xtxs+cwtjPYWIojwe9Dy8OBGfvax1Eb0MZp894Y0BvrHAobxj0wi+O9yRPXq/Bz4X
                    uTK8i5obPvJHHz7x5hi+41/lPThT9j16a9Y83kPBPYHqIr6akPG9n/LDvXNiUj02Zic+Bq36vWP9
                    kL14rLW9Cfi9vQBxOj2oXxC9YRnUvK6upr2etzw9s4uBPTpMHD0ASwy+Z4ycvSEe3z3mjc69WWci
                    vpizU7zUH8o9NA20PfdjKT5Ec/S9z0wMPiPwHT4Rx4o8BMkfPdbEMb6sTSe+PeCjvZATwz3ZIdg9
                    dcMDPuCaJL27LCI92EABPiaACz7JVha+LsFxvRByFT7VgiQ+JbRbvRksIb3YKC69ZIY8vJ6dM74A
                    ouy94jgQu0DnDL78fS0+RrzxPTLhv73l7we+HzwIvdZcA77FfkS9Q499vb9hBj6cxRy+oNwIvYT+
                    9T1m1xq+J2P4vT/Luj0rRWC9wpnPPQdue73HwtU7qc7avYdCMz7c+CY+WzAaPidRTD2QJ0K9DqZO
                    ve3mB77LdxW+02kSPmfsxr0XiRe9tEMqPpte3r2cRO49Ejcxvv6qQj2A9i0+fMO8PcekMr2Yrm89
                    UMVBvaENKr2IG4y9x6DTPVmPeL2hyJG9ELelPVZjOT2g6fq9GhapPMrr1T16l548aHRjvWeZID5g
                    qK89l4VxvcVrCL661mg8Lf4qvjhryT3wYhu+BTTTPVQ8nr3bZoK90A0yvvHgpb2XudE9nECpPQdL
                    Cr0PTzm+ZgJfPcGrLr6Wqqu9a6fBveSt6bvTzwI9CBgJvpkdML2y9s08ZAAzvmU6WL0rh489phzP
                    PThp0D2ngC+9yVkrPg01dDwfgRG+1/CRPfOc3zykcx++0ggGPvnvxj0sa+W92yv4vTq70z1cEQq+
                    jgyDvOywIT1E/CS+3DBoPPtPJT7I1gu+VBwmvhRYOr7yZmg9lSQAvgemrT2ZisI9kYGhPT6MrTxo
                    rBY+rqxsvRtkIL4HrSu9mEMdPQARl73FAQw+LRGtPQpNiz1Zmbo8ikAcvqyOsT2hscA8AvM0vueH
                    lzoDLu09qLz6vLl+lj1Ha7W9tuYuPpjFDL7qtzy9M4wIPDxUFr7HnIs9dgEpvq2dxr2i+Sa+AL80
                    vtGZJb5/nC+9M1KLvWQ5OT5xPgM9+FLTvF22Nj7vQbs9X+IfvoQikD204R8+Zu2vvAXg7D3xoVo7
                    WsH8PciiPD1jM+M8CyylPaEUJT1BZGu8wieKPdCSNj5XcyO+PrhRPX9SHbzKxJM916NDvVXU+r34
                    PgM+ZCpsPUt2GL5iI7o9N1OrPWVNar2NHnQ96LyXvfsyjzwQ4TW+IarVPIKzoz0w4Ki9IGo4PgXQ
                    Kz4x0DC+8g90PdJhS71E3jW9cIMFPCpS+b2Ty5m81+FgPGuLED5qfSW+ELDHPdqf2j2fLTA+SyEY
                    vr5c4zxdewq+mXDuPa/jzb1gPIK8vgAiPrbC9b37yRi+wH3DvSSRiD0NR7a9LQTaPUF+gDxf1P+9
                    lqY3vf3aHL6jwdW8rMCXvQPxCjw3p5+9sSwTPfkSFT4hq+I9DKIkvvsKe71RVtg94n6rvLHwDD7O
                    Yw6+2yKyPQutOj3izyU+mEoKuzT2yT3+lb29yA/QPH/wFj7GkbA9FTpzvbLuL75y9fo9mw/yvXdF
                    k7121NC8nD/ZPR+7Ir618PG9syAdPbFSAj1I/nO9xGc5vvFjFr4EBSs+25EOPdgIA77o/eI9crLi
                    PX+hSLxhfgS+Hro2PsSPJD7Wicq9KI0Lvb6T4D095wC+
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg5MDkwMzUycQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODkwOTAzNTJxAWEuHgAAAAAAAAC+duK9VZHfvQBYM76DA/Y9VyQXvgp/Kj6r/n49CwpXvZVu
                    sz2WBas9CpgDvno0Cr4TCME8B+PEvYp+P73zQQQ+0f/BPSeRIT58TZa9aWTZPZDmqz3pW+C9ZAye
                    vd5zGL4jdBq+6NXyPZqjhz0rw129LwM0upvYBj4=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: true
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzAyNDk3NzI4cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzMDI0OTc3MjhxAWEuHgAAAAAAAACMyW+8lokOPnc32r3hth2+YKfGvYeWGD6ULKE8g+sjPgBf
                    7j1kUf09so0gveaGwT2rILA99+nWPSS1Ir6OX9c91nfzPbufCD66F2O8pr0fvsXq/jyNXpg9j0Ev
                    vu5zA76WIrQ7Ln1GvYcEED5M8Q49vRxyvLgkqT0=
                - 0
                - !!python/tuple
                  - 1
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg3NTk1NzI4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODc1OTU3MjhxAWEuAQAAAAAAAADJrTU+
                - 0
                - !!python/tuple
                  - 1
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 1
        training: true
    - - decision
      - !!python/object:torch.nn.modules.activation.Sigmoid
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  pas_de_temp: 2
  training: true
forcasting: false
learning_rate: 0.001
