backbone: !!python/object:__main__.Rnn_classifier
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyNDEwMjkzMjE2cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    ODI0MTAyOTMyMTZxAWEuHgAAAAAAAABaj2C/rOvHvvB/iL66KBA/xEEkv4xXpr7EFuS+lBzPvuQJ
                    AL8gr3y+tPWovsj7J74+Piu/8DArvsC7Iz6g3r49lLKJvugpEz+gSxs+hDyKPr6MDD+wqCS/rLhx
                    P7CpsT0EhU4/mtRjv5YEQL9URt0+YONHPR4rR78=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyNDA5NDYzNjQ4cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    ODI0MDk0NjM2NDhxAWEuHgAAAAAAAACk6Fa/tL9Hv/QQ8L7ApCS9QKvQPUgMOL7UVPe+3LCtPpDa
                    AL6kwrg+AKvuvrxtBL9Upqo+qPhgPkxaSj+wpWQ/IClWP9BbrT4QzZK9ABcRPs5Rbb8gSKG+jmMk
                    v8guQ79IVCE+sro2PwDGh7zA8WA9QMrTvtjvWD4=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: true
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyNDAwNDExMjMycQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    MDgyNDAwNDExMjMycQFhLoQDAAAAAAAAcdgfvTETMb6ucZ09XNUEPljk/r3n6wG9W0HjvTTeND60
                    nQs9cInDPctoBL4HtMi7V8uJu2ZC+r0loDi99DhpPDaqy7yJpMY9R8UWPXi6473NtKi9Zcbcvd7u
                    IztENdq8HpgQPRopnz1s7QM+VD/BvRMvHD4Mv/w9c23Lvfdnvz1+iAS+A079PBkDlr17U/a7axAA
                    PkxSNL4enIi9vQnKPfr6iDyapNO9333dvZ43KT7x4RI+W40fPgwqYbzruV48kYEhPdumQ717N4O9
                    oX0kPsyMEz2Ap5i9R4EzPqaX870NrQk+cPMovW1qvTyO7BO97EUAPg3ugb2XPzU+zPNYvVdsN76T
                    CTE8DhxZPb1kAL41rPW9Ah8rvQuLpr1WaCC91sDYPf4Q97zzWJG9iQ1fvHgQWz3zCzE8i68evvWQ
                    mb1iBw2+SgucPa5Ssz1gpwk+3/ZkveZWF774lsa90MgOu9BG9r1nbRo93KCiPXTdIT5F48K9mB9h
                    PVpMHb4U0gI+zmGVu1H2bT2+Tpq9Y8tJPWQE5L0Dl5+9ttAZve2NqL1pb8s9CEXruUTxAT54liS+
                    nSksvjIUrD2QYBe+G1EJPvXsMD7oY7E99hWTPSJhE74GPjC+KLn7vaZV8z0Jqr+8bxdrvXaRRzy1
                    +ie+/NoJvoQp7b132BQ9hC4GvgClQb2wa/+9GkWMvIgsvT0T2ee9RCkZPur98z0tOvG99rYQPjG7
                    5DolaQ4+RNsPPvlZ3r1kvvc8XOfVvU5eQL0rVCE+GFIuPnHgrb2jFcM9B4sgvpPqNj6d7ik9/Q0M
                    vQDpyb2svoW9TEsTPbX8Dj5xgWu9PXXcPAODYz192ho+5GU2vu2vdLxu5JM96U9hvbeGKT4XkMc7
                    y/HSutbV/Dv1gRW+YmBZPWHEMDznBxi+isPNvVG2FT49/MI96gv0vaJWoj1n+oo9L+EDPYByLz41
                    ggw+Kb2GPRg3M764XQW+yqAZvohMLD0urLG9CeJFvBRTSzziCo+9Nw2wPIfAar326cO9TlAiPs3q
                    Er4fneY9Z6gZvu6eAr4awfI9a+X3PRWkkjwFR3a9MBS/PC2Tvr3vzAG+AiX/vCm7Mz3FszQ+QUbP
                    PXqD2z0uDSs+Ozgwvt9vPjwDrN88xbamPYPZxT1nZO89gkDYO7UWlzxGZI+97+gjPuE1eb0ypx4+
                    0zKQPVJZrD0KYNg95VUPvWt2rz1c5wm+zK/ivdw4NLsTGeq9iiyOPaIjr71+gOe8YQiVvUju0z1h
                    3J89b64DPpW/pD1CkEk9AXS7vc81XT3vneu9X5jXPcFzAb41tOe8NpU4vcZSqT0++Te+6cG5vUCK
                    4D3hyDa+AAbyvVoZtr3UcwU++UQrvpWGjj2aQ669UlfHvQpULDwpwgY+tTxXPefxgD02CxC+V1tn
                    vS8dFL5cLs+9HsYMPjN/Sr3z65O9khFrvd5ABj7n5fw7X8dUOkGIZ72LS7U8704gvD7eIr7Ubam9
                    Zvv/Pep/Gb5voga+VtgMvq04HL5KZ/k9uQigPQRl3T2Wffo9y9DrPfb3qrtqDpW9s1YCvuWlE76R
                    ku69bKUVvitjdb1W2O+8jac5Prj2Fb3I/xq+jGecPWMMoL1Po/29oyG+PTCf2b0jBRU+97HsvZZ2
                    pD1Uci4+Fu66vW2gzTy1UhS9uybwvdphSr245ri9+dztvadNOr4Mug0+EXrjPUEiIz7OWxu+06+d
                    vQymxL3ALTm8yTzsu6zLM77LsRK+tMx/vJo5V73Qdci9bEvvvejyCr5HluC9bbUuvSh6mL3/LnU8
                    spbxPWWXMj7yxtO9pWQIvo9LOD5MSlA96Dr4vPpHAb2wrE+9Y6VBvRbbKD54NyE+SzEsPgtPUD1h
                    lhO+5M6mvWjNFT6sxxe+sgYXvuhHtjx3Ah+8P7XPPfIXgD15B+w8WrcbvuxkCz2nCGq9JBlNvAKU
                    Or12hqg7iCFnveV0KD4vj9A9VTgevT8+nr3wELE9qs6xvMH+hL2g3ym+I5L6PdNLG75Id0c9V/MK
                    vUfHIr2vAnQ9q3OBvakB4L3+su09fpiJPXx4wT28jBC+/lWwvakSkb05Cym+ovEWvjZgFL7+LKa9
                    jlASPn99HT6WwrY91OUqvoJQ1b0GSxy+atIjvm0I9TzGRJc9amlwPex5qL3XFoE86ojOPQICorzV
                    ax0+GBscvSIkp7xbfjy9pkUIvmSnzr3ykyo+t1bRPeuQwr3vozU+fdYQPo1C2L2fjNm95QUWPjgo
                    wD0IWMg91ikePombEL5ZbcE9yim0vd0/Ez5Q47a9rI6bPSIRBL0/iNM9f5ixvQjNLT3luyC+3FPz
                    PZXNaj254Qm+L7oqvqvU2zqSnRC8TxMkPr7EUr03fb89CvWjvQae1b0zQi697elwO/PFJT6wc4s8
                    fjcKvT2+qD0HzzY+TYa5vUCLAr4z0M89pL8wPqeyHL3y9Y+9yvAzPTDI7r1wOTm7sBoVvu0k8L37
                    h1O9tcxrvR8YOr4rDG09+XgRPq+jFjs79aa9eaZevEyRAD7qsua7kXgAPtifhr1O0zC9ek04vk+6
                    ij27S6y9RSw2vgzMJT48ic+95hYhveBKs7xWWg6+YWm3PXrJFL47Xp69v11/vT/T5D0ixnw5lXEl
                    PercPj3CgoK8zHe2vdiEzL0WFPu9ixNhPT8ZNT00T2m96CyHvdSVmT0QXi499OMsPqCAjj0oZSw9
                    thI4vpmRq7yT5CG+s4fwuunasjy/9oG95YYoPmgtEz5Qozc+g4+svbKxlr0ib7G9e8xzvfFEHj71
                    8jq+Jx5RvTv+sz0yyKc9b18EPWBFDL14lLS84fMKPhBjLr3ccFw9qSWHPSvYL76V3Z09z//2veDS
                    Sb25bqY9Bo4wvin9sztHdwE+K7gXvlkpkj1tGXi99gqTPBz3qz2+Zok9YOSlPcbeN76dtoi9kl6a
                    PS249T0ycjY+Gbe6vWSaKL5aqhM8ar38vDAIHTyxg9e9K5KIvVxJCT7KTdQ9k8lmvXN3u7yaFRM+
                    zO9TPZl6Kz7U9iu+cz2Gva6p2r2pT589Qi7MPY/xkb1VVSw+1CWiPeE9zz10uvA7Y56OPX8obL3O
                    4Ti+UBTwuvPPhT3T+Ey8v+rbPfarybwwGlA9wzgZvY/jXL2mdL29SPpgPWI9Nb4FwHk8OSAzPin4
                    K71DiDw9xqciPgCtBL4L1Um8mQXrPXR8Er4pEg89m76UPXYqKL6YhDA+w6auPauZ773RbQA+H3ZP
                    vU4ucz35x8y9qcvXO8r4ET6MDS69FJA3voX9ubzvgy0+nk42vqPfOT54NTC98lR7Pcdn4L1AefI9
                    GNCdPYglxj0Nx9O9nROevS0RvLztrjY8Vg/ivdaXmb09Hx090zEpPtXN9L3DITQ+eLkmPpVjRT07
                    mqo92wiYvUssT72PNEm928XmPXQbNb6W5Ze98gAbvdtL+TwWqSY+OGiZPd9O9j3riBA+hvACPrFr
                    qL3jreE9RhcavYWNFD429BG+o6C9PY3V7j1JWnC9wP02vqxp9r0+joE72XmmvegSE77h+jC9gVQE
                    PtZdfL3kDyQ9YfU7Pe/NDz5ouCQ9VSI4vgiaobviMfk96hLyPWhjx7135aA9+/D4u6HtyLyxvs69
                    bB0APRoGSz2Ebik+uamXvMnlOTyaTec9NWjKPfBPGz4xdqy9+uoevg4B2L2fqOo9fJ9cvZDahb2j
                    Gt+8/RclvsxXjruINDi+dbUxPuwj+z1amQE+fmDQPeD3fb26Giy+eUKkPXp+IL7p4f09hK9HPV5N
                    AT4z3MA9ZCrTvYDcRL1Ijxk9gd/svEVJ7D2QSDS70mIfPX7Wyb3PvQQ+Y/m/PZWHlLwcSxU+ed8f
                    PnKNDz1UhMi9ejPivZm9iz1ANp+90Yn8PU7/vT2A3SU+j2qVPSc3PLxc+I08WPAvPRNAdD2IZSO+
                    kdVXvRSCGb7TJse99BA4PvfUTb1BQTC+ov8yvRSl0zwwEwQ98N4HvE/lq7tf/By+x806Pk/5Ubx/
                    w7I9E1v0vEMl0jw9Geg9hYWRPRlTCj71UDM+HkUOvjbfCL6jyQ++zDgkPuA5Nz7GD669CfYdPm98
                    HL5SAqu93n4RvgbNgD2GEi492H5XPVb9NT6fEAo+7BMqPmxA3b3iiL68sMkDvreRkL2aQ7i9S2Kw
                    PJuBLz68DBk+by44Pp89lb3Egg+8UHskvVFKHr51tx08HP6UvT4Gxr1eYgI+6lgbPs49VD2AfK89
                    +A5BvagDGT0S7Qw+L5eKvTiz5byeFxo8pj4Cvo26pz2VTk69DjeePboYB75s5iY9Iig5vvqTn739
                    yXw9vTOivdQKNb7HMQo+i34VvvaTuj0IOra9hpwpOlf2lD3U45u9+l6Hvfvu4j1fnYu9eeMYvo4r
                    hr0FdsG9xqR+vT1EbTvIas88u4T2vcS48DwWgqq9UYzdvc/qIb55Ec08TOBOPRXDYr3YBfc9H/Qv
                    PtaiH732XjA7WxUIvq2I2b3l6rg9s2KTvdt12L0gkNk9RugPvLjnC75UrBG8ofAlveWYoj2DE/68
                    BuG+vGW8FD1igJu8YlQevq2DrjybAWe8mC6DPffkr71BKA89gFIEPrhhlj0F7yo+siLVPQ2vLDxe
                    Gd49yjIsPs4aD77NsxQ+3ac6vYNUcL1DQIG9bdeYPCqfQL1QHAc9ZogqPh+quj3aUrM93bAGPktF
                    4z0yDQc+JPFkPG30Fz6wHk29f1m0vUkIrT2vNDk+DvxbvYcoj7xKfYI9gFzDPWMXnbxAQRW+Byj2
                    Oyp6kD0BB6W9PrkbPvRyLT1bt7I8rbEePAJvpz1E7ey9
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyMzc1NTY5NjgwcQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    ODIzNzU1Njk2ODBxAWEuHgAAAAAAAAB2tzE+AgNBPdIFK77g97o9nBK+PSZ0/b33H1i94JsJvlMu
                    RLzpmis8d1XkvQsFIj3zYP+9EcPMvcIuDz4TMS0+GpWBPaoBsDzpcZI9ltqNvS/Sz70vA808nD+O
                    PXemFT7sqhC+ZQfNvRI/mD2ExrS9XxCoPZ0wJb4=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: true
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyNDI4NTU2OTI4cQJYAwAAAGNwdXEDS5ZOdHEEUS6AAl1xAFgOAAAAOTQw
                    ODI0Mjg1NTY5MjhxAWEulgAAAAAAAADkjQM+nIgOvvF67D1s+sE9mt3NvddsH76dvCo+1TcMvoVb
                    LD77JAu+NSwkPsQED71JPge+Lir/vUulKb4dIEM9jvrSO3u1JT4ojLO91XMCPoamcb0L/pW8UDO3
                    Pef04r1noEW7GicMvvKLir1znDc+akYQvU1/H70zgx8+y6COPWOqcLtyxU29xagJvtY3A74vZAE+
                    Z1NFveWWNj4auRY+AyU0vunAmr3IiDo+LAIyvVSaDb73XTo+nH2UPcbdwz0i3TI+rGEWPqoakD09
                    aA++otoivvQqHj5A/ci9iRIjPqto5DsXIDg90kkSPe3y7L26xx0+fxGxPdpElzy6kP+8BMxQPWAb
                    aT1KFpm98Zk3Pr2u+D0bHvi9ZKtXPcbQmz0Ruza9w7FivER7pzzMhQ6+OX0kPij3j7w7rAk+NGsH
                    PjkKJL5av609/2Qcvg2TU72AmRs+T5ZRPW300Txl/gu+FcfWvGH5Aj7JGS0+F5zQvYB2Yb1AkAk+
                    mjErPpTeKb4iCru8vehRvXYQ2b0Pgy4+5Va4PesCLL564609JNmjvD+SXD0kInM9zhChvdyO+Txj
                    4QQ+ZQbqPTtHOj5LF7w8wpIDvvh0JL7ci4y9zBYqPgzLDr3+5ti96GAWvqGImr0XKfq8tMLaveT0
                    yT2DcMm9+VXYPSokgL0yZKG9XgEovPigjL3MCSG+wlRlvWI/E75jNjU9+fWevZy/Er7xekk9KXoL
                    PhIM+r3qkps7PYW5PeSaDr48XpU9dLuPvaKNJL7TsSO+cVMLPWQmCT4jgPS8ZWk5vugQUj0=
                - 0
                - !!python/tuple
                  - 5
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDgyNDAwMzMzMTUycQJYAwAAAGNwdXEDSwVOdHEEUS6AAl1xAFgOAAAAOTQw
                    ODI0MDAzMzMxNTJxAWEuBQAAAAAAAADGw4E9Lx4/vci64D0EjQQ+h7O7vQ==
                - 0
                - !!python/tuple
                  - 5
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 5
        training: true
    - - decision
      - !!python/object:torch.nn.modules.activation.Softmax
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        dim: 1
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  training: true
forcasting: false
learning_rate: 0.001
