backbone: !!python/object:__main__.Rnn_classifier
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1NzUwNDgwMzUycQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    OTU3NTA0ODAzNTJxAWEuHgAAAAAAAAAgrb69KMxbv0J5D7+AsD+9hhF+v6Q+bb/Y7hI/4AVEvbSe
                    Cb8EVWw/RNdSvzR0AL8WxwO/8IBUvgDbkj14cUO//JXWvgaLTr9AFAM+FrxCP7Q+Uz/41D+/VH+T
                    PkZYZz/i5Eu/Tjhqv7hUKL68nnI/QJxivWAlXT4=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1NzUwNDc2ODgwcQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    OTU3NTA0NzY4ODBxAWEuHgAAAAAAAAB4em8/WNWbPpQNxj5222u/4OqYPu63Mr8Ct3y/PkdeP5BR
                    Cb5ELfS+sIpGPxJjUT9Ujl4/XPK9voDVhT3YpyO+ACkpvowAMr9QetG9rKpJP/xKjT68wFo/+IXJ
                    vpyhOj8wS1g/qDgbvq5yIr8s+Y8+CG+ZPiDAiz0=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: true
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1NzU4NzAxMTIwcQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    MDk1NzU4NzAxMTIwcQFhLoQDAAAAAAAAqz4GPREtNL4TLgG97wSjvdN/GL5xj4y9nMHmvJXHJ74b
                    CBk+lCIlvg1GqT0mdd+81U+jPfaXNL3JvQ++zpaMvHyIJT5VuSq+5G0ZPqfLI70Aydo9selavFIv
                    0zwnGgu+wKHePXSQ/zwuTA++ezUZPk5wID5qjQQ+nYaiPSGRQL30J+O9d9I1PiN8Cz7VmGs9TKpz
                    vSCWAj6NMGw9XGEzvuvggrsXXJW95FSBvSuXHr7ltZ29qM3TPEMXFr6CVvc8BFEyPiyFjD1orbk9
                    ytsuvozbDT40MsC9+8SEPeU7JL4HL6O8pBMJvqa8G75idQS+9+UVvkCeoD0WPfQ5UPwYvoZ8yLo0
                    qpq9qhoQPMc7hT0FeoO9T/8svhAk0TzLlps9KOsfPp4L7D123g898F40PraS970E9qi8hjmqPaE/
                    v73cFY89Zb2zvBzt7b3a9RQ+AGfAPaPZLL6ebAc+65HBvNuaGj7Q7Ry+t4AkPk9iOD4LPpw9puf2
                    PaWk8j1BaJm7T4RQvXHQU705Hpa8670SvNZEFryJ7mI97pHnvKWT8z0z8iy+ASX2vckFNz4ocgo+
                    y/jXvWAhNz0GSCg8qKhRvbfh1j2huQq+Xbz/PTq2ubzrLoW9p7iUPXWmBL7e+Qs+6MWMPTd99D0F
                    5Tg91SM7vdEdW73zSLC9vSaXvfudpb0lASK+PeCgvUWwrjwNZCG+oQZ6PYj2Hr5DQAW+BG7GvSES
                    oT230wE+nSMrPgt4orzP+gA+eE8evr86gzyEKQA9+OUmviXHcL3+YKk9hR0Zvl+Xpz2Efay94SeJ
                    PcMoBr720g89LZQXPmO6Dz6Ul889s+YPvat+DL4PNi6+10FwPdkbGT6kRAu+clEgvurDKL6djsy9
                    Q/SJvXJ/Gb5bfBg+J/wpPgVe1b1oOTo8tlWxvWjFpbykPqi9rsn8vax5BD7P6us7dZaSPbs+Dr7j
                    +lY90VMgPb0X1T00njg9RtUHPsM03TyqQNO6j5bVvaCidj3GMss9uKcjPpDGGD0bQhM+RnAxvUzh
                    hj3fXjA9tLsgvdbgpD17PHC8++/sPRIeSj2i7Qw+m24evVDy8L2GvEc96MQrPsTQmT16ODE9SOgr
                    Pqb0Lb43s2u9YSIlvmTstTx0Dyw+Jn1gvOpKxr2emNI9B0obPsCInzyQVSO+myb0vaTJnrxvde29
                    qJYQPW0ourz4wSE9dvPTvR17GD5ttQm+FckrPv2ItD2fqry9pGIAvQLG5z0H5sA8GBqsvevOnTyg
                    b9w9u+8yPo8a/z0EgjS+EKBYPUmMLz6Wphm+5L8JPkFxv71PORC+utcEuwpzBL3TXq09apk9PQuC
                    Fr6fy6Q9IopuPRQtHT5m6cm8g+cfvjWb5L3Sdfi9eOMOPOm8Ez5fYhq+f3KiPa8qwT0bHgS+E5KA
                    PYQKIb79Kge9liNyPFl2x7jIn+A9ZrP9PVeFBD6v+FW9VwK/Pf3Drz0kOv89c2uqPU6drz1mNyM+
                    ckQjPuI+MD55hJk9pYc3vp4iur2xfJK8Sx+nvW1I1L2GNz49c/UDvU0yh70QpO+93HUVPlN8HD7l
                    ehk+A80OPSVrnr2ubuO9BsEMPdDQ373avi4+VWMfPjOP1bxtKS6+nXffvCgYzL3K0Rs+vajEPJRV
                    4D1Zbos8HmaRPWBNOD4KJzW+CVF8PRnG373w0hu+ncsnvl4deb39XQK9M32svVuX8Dy0FuQ9oE3Z
                    O6Lwkb09NmY9AJYuPr2XDr6VVBw9OTHoO4c2Lb5ELzi+C9cOvme8Ar6Ylc89/lptvb1PFL5F7S4+
                    dSMVPbSoGbp4elm98YFEPNZFFb5LPgq+iarCPGSUtb1Bu3u9VO2VPQVBNz4qOhy+NwQJvjnhRL2n
                    cga+/3WTvTNL0b0Ad5O9A54SvTzHuLxNT3w9EP1VvV9utT3SsOE9LxIfPuQqiLsQLRq+sUOAvGnn
                    HL5DQ0A8emXsvTnZS71zpyG8UFHCPXrUOb42eSA+BLPXvBwc4zxoGoc90P0CPoVypr00CuK9Vt39
                    PTOTs70ZbA4+C/u4PTC8FD65vwE7Ri8FPg+y1L3EBGs5ZsUVvqm0Yj1D7LM9Y39HPEREFD5Iqu89
                    iLSXvRE82jzOeKW9DAoZPoqPZr0qq1c7Vt6aPXRDjj3qoqa8dX4tOzaEOr5oeJu9OtUOvhOoIj63
                    F/G951uXvexxtj2m0Ck8VBkWPhqn870Vwxg+xRmqO2Po7jyuSCy+mpwNvl6lir2dFD09drtUvZs/
                    OL0VigI9RUsgPkKawzuI2DW+cy7AvNFziL3orTK+HhAkPrhey71x0Bs7svAdPDqyzD3tq5c9b536
                    vMkcLT611hS9/DayvZshAT6Lsqw9FxQEPu99N75c8ie+YfAVPnX9Br71Gq49G7+MvMMYfr1DI5G9
                    z6gavWrfjT2rNRy+vTHdvYgLHb54oxi+o7a8vdfN5b1h5OI9xnWAPfOeE76UiO29lcf4PbEMJb6J
                    Gpa91LxGPdC9MD7kNz69Ec9qPQMBOr6YJG88h2DDPev/r73fPkG9Ig3svFU9N7zhqeC8cZPePPXl
                    373cX0i8uWaqvUEGDD4RhN29rbIHPp/0Ab1fnvq9UH9evU51cD2QvYe9mOnJPRbSAz4q0eI7rswq
                    Pgc/yjyJy7C9nOMWvvn6nD02wJY8Z4EnPvxRGT5qvxM9/K4evXOCxb3/QQ0+1on8PbpJJj5MHTA+
                    iFgevtIa2L2BfcC8v1YRvliUqj3RooQ9lTQ3PgFFyrzyuuk97U0BPhFHlL3Uar49MDVYOgaY8r0F
                    qh6+jus1PgtWQL1NYJy9LriaPRkbpT1TY5W9wFGRvS/rvT1lk1690LKOPSMb4jzsaYs8pUsmvCH9
                    W71KIi6+CM0oPmvU47pdQOo8Cd/vvTNwAT7UE4E8Pn80PNDjvT1Zg+s9GN4SPmLiE76mX+Y9xMim
                    PUCIMj10w308KicqPbXe272P2jm+o0bVPVkUEL6pO5w8T5Icvpi/hz1ehAa9slgFvS5tm71kZdi5
                    lWOsvXDTD73dlEy8rKkSPcWEcT2s7ZY8qNkkO9ivxry31xu+PX8Pvors2zxBvjA+er/CvV2iIb62
                    kxC+acL0vJjQDj1hwnU9e/HtPUGHW7uOZiA+a/oEuzDPKD6JW7a9cuioPefTGD426HM9IMfcPBwK
                    LL4+/HG9fpHOPd0CRT0VWRy+ZhzMPdoyHLz4NZ09NyK8PdSzCb7//Yo9ZW/mvcFYLr56ZdC9IQ60
                    vepUr71zWhs++ZcCvjsnNT64VaI7kTsavpEyjz2Wyui7iZjcvVQTsLxWCBG+jWqFvbkQ/72W4Bo+
                    BKZTPXWRB74tLyi+obD3vfAi070e9CI+Lyz7PS2XnT02Jq89W5EqvdjIND6JizU9WYcOvrM3M76/
                    wXe9G/nZPHxkETx8f+28pCsUvi2TM74ad/y90d7IPa2ssrsx+EC8+BMtPWNCJb7ChqQ9OeDXPR1n
                    bT31Y928uY0UPR7Lkb0QOF49pZJKPbG0Mj6sbPE9cr4wvgKAZTzFN7I9lEYPvtH7rT3nVsG9aegG
                    PjHmdz2cDy09qJhlPOA1h7z1bj48dYIFvUoenT3LxJE9ONAZvqq2Bz4/nCe+DpIovb82LT5PygY+
                    3YgEvplZ0D0lw/W9KVogPTF3Fr7TUt89l1AvPdeV+L1o5de8c14xPs9sOb51cJk9WZKgPE8LAjxd
                    qRc+0qKXPfTpI77RPf+9Ol0dvjuZzrw4OfW97/mxO6yKKD6wsVo9RM5wPA7U0r090SO+otcIPuyu
                    7T3GrBg9y5K4PQcVMT4b1k09MPonvlUByD20EOw9sDGLvOTCML4q9C6+BMRiu7tBeL3OZqQ9Iox9
                    vN2gMD5y/e+9RBD8vbBmLb6JM+q8LT/4PaRDKD2Gt7E81BlVPfYDG75GR2W9bc2hPO2B8D140oU9
                    bXqQu2oqQj0atTS9zyuKvcZ7Db11ygG+J3EDu7OHxr1m1DO+CuWwPeIyBz4TFSo+Iga1vWxVcD2B
                    xBw+MPbvO7iM8zv0CVQ8sF34vS4Vn7wThzi+WafIPSA5HD2K8jk+/Z8hPcalyL3ikes9ADqCvEWD
                    BD4RxyO9OhkuPrc0ur1yXje+aynZPfyB6bw42AE+ILIxvrs2KT5yjDs9Yk9vPfz/B75PE9c83uwP
                    PsQI8L03Jwq+xcFNPQoIar2fHAC+Z5YKvmeF5D2uhAi+3ZOqvLJbtj3ANdW9SCdqPV7lJ7428Qy+
                    WiAqvsWSmD3OB4k9OzDPPQkhlL2VDQs+4xXivZxziL0EOxQ9P8vgveKwFT3okCA+/QljvXKPKz7i
                    zti9Jlq1PGebOL5xM+075pK5ux7UEr4k/iA+ZzqGPZ1qDT0G+w++fL/hvNUW3jwxudg9+44Xvpxe
                    Sr2Jhxo8LaDYu6lsH76rYwg8KeYjvnoefT0Joxc9OvujPTpA3T0HOjE+653mvJ4c7L0vtzo+q+mI
                    PdQuIrs1NxO+4cYVvuZ8Ir7zdxQ9bVNePUC2vb2ZluS9ZWYSPTekXr2AfKS84SebPZGQ9L169U69
                    dME6vnokMjvTu6m9HV0KPqaNBz3XKb29s9Mevu04gj0XgCi+El2AvPgUDD0CVeS9pNn6vCHsAL4f
                    d5I92Q2avAP2Lj3313g9ni0VPiAfT70WUcI9fyxEPXALJz7M/QE9TEkVPhFTMT6XFGq9OENkvR6k
                    Aj7tlLW9aQxEPcfqArsL7Qc+U7WkO3lSML6TpDi+qIKmvSaX4T19pkM9GKekvTrbGD4gfNY9YzS3
                    O8o4nr0ILpe9A6PSPeVpDj2jDQu+ADa/PYKhjL20+i8+
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1NzUwNDU4NTkycQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    OTU3NTA0NTg1OTJxAWEuHgAAAAAAAADr2/I92Oq2vVL8HDxk4wO+iushvrI2Y723m+I9RUtqOxpG
                    EL4NhSu+N/ogPlTqoD13YdU65qkKPYcSk71UhBa9PD6evSy2EL6xNK+9tCdKvVrMtj3/YSk+FWvt
                    PQz/3z3stC8+pf0Rvlc0vj2qSoM9YcYWvs+w9r0=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: true
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1NzUwNDc4MTQ0cQJYAwAAAGNwdXEDS5ZOdHEEUS6AAl1xAFgOAAAAOTQw
                    OTU3NTA0NzgxNDRxAWEulgAAAAAAAACoAjG+Yj2qPQ79HD7/pxk+CqwBPp4/JL7P+dc8hslAvVO3
                    mr1pLR++DV84vtAwxT2mR/69d4E2Pe2uaDw14Ry7lw4WvbpUdzr7mdS9ccDrPWZaDT5pKzU9GI2w
                    vdnvFj5oJAs8SXHaPfpeBz4OXr09uL0tPB8EsT0AysA7A/0hPXix2b31Tv88rY0NPr2eDb7ffwo+
                    sTaCvSWGXb3PD4S8ZDQuvW9YAb6jnSq+3n4MPiMYB77jYwE9w13ePNrwmLuRNqy92qgevpcYLr4l
                    Cr49XMPDPeWI4b3Wpjo9NjcfPl71Hj7WWSO+Hp5hPbTRcb2xL6S9vLsjPrisTj0pPxK+Sl2rvQfk
                    rj3M/Rq9ZjQSPnAU+72M3R0++QsQvtKoIbtnYQQ+bzGjPeWqUbzWU949aWFOvSF6Mr5lXR4+r9UO
                    viocHL0oPF29PW2NvFDZHD21eS4+yuwoPgzgET6nf7O9XR3VOx5ox70kIQA9ioa5PQ5DOj5k3gc8
                    by3uvT8hpD1MC1e94GABPEq+Ij5kmju9cNLTPa34G74iXWs9Aa8mvoMa2L1oryk+ybvZPUlLND7t
                    d4m96g+ovdj0jTurWIA9/WkCPowNNT7S0xC9d1eNvJj6zD22xUA8jGDFPD/Pzb2PQDO+sDzDvcvY
                    Dj5L8cy8TORePd7d0r3OC8u9KbeZPfB59L0XQfg9a1suPc+BEj7evS++yuuvvT7KQbzssB++Hz8W
                    vr+MLD6ivZo9OKAFvWnHq7wM+289ij0NPIzPtb3tsZM86DgCvn4QGr7Sx5297uAiPGoE2r0=
                - 0
                - !!python/tuple
                  - 5
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1NzU4NjM2ODk2cQJYAwAAAGNwdXEDSwVOdHEEUS6AAl1xAFgOAAAAOTQw
                    OTU3NTg2MzY4OTZxAWEuBQAAAAAAAADQg/k9jejavSc50r3qvPW97wIKPA==
                - 0
                - !!python/tuple
                  - 5
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 5
        training: true
    - - decision
      - !!python/object:torch.nn.modules.activation.Softmax
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        dim: 1
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  training: true
learning_rate: 0.001
