backbone: !!python/object:__main__.Rnn_forecasting
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzUzNDc2MzUycQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTM0NzYzNTJxAWEuHgAAAAAAAAC4F/Y+LiMXP0RLxL5Y8LO+tBIKv2ggGr8gFS0+els3vxLG
                    Ub+afUS/hqtQv1j1BT/qIR6/SsdHPzjJFD9QY8S9rAEUP9xxyr4AXyY9+ORmPqyLGr/ANZ69EA78
                    PUzQmr6IURK+tOSFvhSieb+YHGw+6EkxvgCxLL4=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzUzNjM1MjAwcQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTM2MzUyMDBxAWEuHgAAAAAAAAD4k9E+2Bb6vlZeGj/ox1s/TNwzv7xxdD/Y03+/2NPyPupZ
                    L7+KHj2/UDIWvnYUYL9MLE2/iJ1VvkDRrr5Ah4g8INJbv0B8Kb6SbXS/PDokv/h/b7+URsQ+MEd4
                    v5Y3Vr84siM+XD3WvtjZ/75A1d29POz8PtAdz74=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: true
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzUzMjc2NDE2cQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    ODQzMzUzMjc2NDE2cQFhLoQDAAAAAAAArKXoPaZl0D1D9B8+Jbbcu5oBGb4tEfs94OIyPfzrS7z5
                    GA0+6gnePPJFLj48gAm+I301vr8hFD6wYou9ySUyPl+Dvj2Vd889jhcCvoM1ND5F1Ac+OebdvZfJ
                    vT2/ZCC+5IJnPWiNJz0Q5y8+P8cUvrKwOD67TCC+UJHyO36ltDsLjhs+fwYuPm1qB77HT4s92nM2
                    PsrSMr7nrqu7wSatPVMU9z02lbQ9tmQsPgWeDj7rL0e9JLDRPW7EmT0yC609s7prPQe3ob3Tjii+
                    NWb6PMqfsb0PQOU9uv/IvaS07r22GJ09RW4rveArsL2xbnW9eG5pvaDec71aIA++qlOfPAqz/j2o
                    h0O9Zrq7PdRg0jsFLJ28YsbHPR/uyb1NXgi+hgYRPnQOL70Jd1o8+FQoPpE4GL3hUIy9M0TEPYO4
                    nr0zdLS9eM82PnQQyT3B1UO9L0dGPbM69L3jMke9KORZPLVkuTzV26M8kQbKPOw0wb1eFd09Dfa6
                    PMjNIz4k/sS920S/PagqFj7P8uC9kiqlvQr6Kj0gEGa9FM/Hu2g8DD2svBm97Ui6PK3EQbzNES8+
                    DCMSPtXf4LkVXik9eMJZujh3XbxHb5Q9ljkEvnKWBL6QkUC9rZMRvtJpz7xSOyM+YYcoviPnOL4r
                    2w++eA+BPbiSDD67CLE9Ms6pvej5ED7iQyw+wGbAvTPAkrxQwiU+DKU2PmxTiDke1zA+0a4rvgnX
                    LLwxXZS98AFMvQK2wz06/w++4aUHPgzw5LyXJEA8BQHuO0c9Kjz/XQs+j0E6vtSHi73RuRi+C3wk
                    vfb5qz3Zcxw8So2QPb7t4L3aa8E8lXYKvuXwqT1suJS8Sl0evrnrDz441DU+N8gXvnxVVT1TMdm9
                    I//tPaqLYD0DGfC9szuePQ9kCL5CKB0+wBsdvqb5/j1DSRw+wUkZvns2Q7wm0Y09pWwKvum5Hj7K
                    7i0+ro66vfyzrT0r0ve9djKcPYr8Hj4bpQ295mV2vUdXHL5Bhn89aIDhPKjtlTyti8g7srHnvHl1
                    +j3WluQ9LVJrvTJlKT5t4I+8CjeOPQOphL3mNvc9pT60PXRdszxcLKe9d4mbvCxcpz1x5BG+GQr6
                    PfFMSL0ngv64cNG8PSD8OL5bPQm+FC47PUtQCj742FS9OlvkvUZtuD2RJzm9beUJPYeJqr248yQ9
                    RwbJPYwJJb6lbjc+jDwYPtxAV72KHxs+Iqwtvm09oj24dRo+NdeaPQ2nqz09z8u91aJzPbruuz0S
                    JK29fIgUPps9mj02GDY9/FMSvqpNO71oks49KGQCvtsa6zv1zKc9SFfsPYKAJL7seF47svI3Pdo/
                    A74CegA+SKPNvYc7DL4vv+A9Vs8nPogao7vfhQy8Fi20PSy5DL2OPTA++P6ZvapDAz5QDzM+A8ZF
                    vGlRdb3mGR++PXcDvrQMFb3JGsA9mpQLvink2j1FbKc9JOMGPpPgELx8SDU+Rj4SvsY+Fr6kJjM+
                    jkrrPe2l3jweqm29gtkNPuOM1jycH4q9t+vCOkfZCjz88zi+5lCIPadVFb48wt095uO7PPuHI77I
                    4DW+CLyjvWL6QDwfLtq9zggWPuOEszwVSyU+HIQRPrzsOj5kQ5A9OFPwvTCq2bsh29I9qOFVPQ5v
                    /D18qeG9hQwVPec+CL38STG+MhIFvbgqDr5MGTU+W5jPPTVBFr2DSSW+RNyNvVgCFz6OhK89pcoq
                    Pm2+FL07IpC9L4aRvQg2MT0rYGs90mmvvR/8N741NNG9EcEpPjVSeL3fRqk9DUg0PnEwLT6g0SQ5
                    ZWpiPdfN0Lw5/RC+GsPFvXSPI75k/Bm9BKPJvTBAGr7y/0m84TDgvRRzMz7RfYI9LptNvXrcKj63
                    19y9bEUSvke+Nz4IXQ09CDwnPjE0FD6CpH07mF/YvWSJHDxrGxW+zLQqvccFkT2mD5I8jvrqPSKY
                    4r0d7AY9V6fFOp7+BL2kIpA9oSSUvKYMDT4hE5K9vuU6Pj0zKrz9jjo+TOucvL4erbwvh/09EeIN
                    PmxHnz2Y05i8rH6muxWuEb5bg5K8tDgIPlM91L3oByA+7/8bvnf9xz1xyo28fLoIPM0eEj2Z5je+
                    9QofPuMOEz0Zlzm8pDrzPQfZrjzt7Ri+KzHXvTeiJb4Oks89oELWPXBF+718Axy+q2TGPYMmEL6F
                    3Y29e8yePYI0Ob5umRc7mJsdvkY1ur3Obni83Y4Ivj3O5T28DQW+D+Abvn8q2z1pauY9ULBNPJQZ
                    qL2K21U9rQfnPGQHl70V4gK+s/OJPXUWzb0iIQ8+VoUYvvNeDb798x0+YwAjPgP41j1pJG89D1eH
                    vRKWCL5Q8jQ+65k1vrm3Fj0Tc+c8AvvNvTn2wT3Nhx69D9QlPcfW3zyNS7u9TChEu3S6pT1bLiq9
                    tiqGPVgtQb2B25m9NRfPPKGpFD7BlI69wUzqvSs//T1t0Yc6iHZEvKb7zj2s4k68nVpsvfSc8jyg
                    Oqg9NOgOvuznxD0bYzO+6iM4Pt5rIb79//k98KMavrokWT1mcDs95pM8u824yjwrdyA+oWXOPT2+
                    jLwbF8K8inEmvhQHkT0JiSo+LevWPU1R/bziEgW5qNM6vlwTMj1g2fk96EimPCKHMD5KPjU+6/kO
                    vk5A/LvPEzQ+ttZtvXVlg73SYts98hU2vtlVYz1+Vyu9d187vSBmc71vbx09zarRu3Q3jz0bQi8+
                    1C4uvtg9ibrHfhe+h36VPRK0KL4LSCA+BuQlviSD1r3NnQg+eAzaPaB1mz3gD7W9jT5uvZIxKL7P
                    4Ie9hqiMvfrX47wizxM+G9Q7PK+pEr7MmA++nv/YvOBZlb1g2Iq9y3cDPju2jT2IQ9E9RYLtvcJh
                    Ab6KcGo9eQ0FPX5e1z30Xcu9DqqFukJWLj6EyA69VUfjvR/c/L25IAy+/iI3vvbRtL2HuBW8MTE0
                    PFC0Mz18nDq+c6vUvWUChb2WkSC+qobYvREzFT2n5Aa+vc5SOwbwITqZWhq+3S0ovq5On73TRbS9
                    Y2kBvhaTyTxaGHu7PNVsPTOi4D2rMLS9FS7APWdCpj2whJQ9MHG4vUpqCD6fojq+FOwUvh/H8L0c
                    vBu9ufwPPK9HBD5U1qw9K61aPeiUFj7Tjv+95qanPc8Msr0Zg749JrsjvpvUdr1vnTi+eTmhPdpu
                    L71wmxu+qpU3vgHyX72AfyC8OPzRvcT+D76jlri9+0O9vc2HirynLJE96DKxvXjzaj2+BZy9JhWn
                    vZFj7rwoMhe+4q67vQacozwu7ha+6q0FvnbiNr4UYrS9y8A5vQG9Dz5P0Te+V3oUPtvxHT7eBqm9
                    i9QNPhXjDb4nU809H34TvbATuD1Fdwk+ieMAPfvggLsze+69JxRzvaMRYD364OW95v0ZPjxifb1J
                    TZs9yfEbPat1FT4gI/49o8aBPSdjP72BE9s7ffXVPQWMl72g4bo9eLjGvd6Zn71HxEi88xMMvoLR
                    6r0Ju7A9vFREvS09vLyTfA4+zADdPZC5iT0OHWq9hbsHPOx25D3GiSC+zGv9PSSiPDo+JSi+8STY
                    vNgBET6qaMa9JGwUPtvxFb4Ar+M9FtwgPhJgI77iub69yKfyvZWKfTso0xe+1BAqvnMKAj4HbxK+
                    hPrGPcVniT1rlUM9b++lvUdrIL1CWKc9VgMXvi9Q2j0wXMw9BpwTviiyOD7rXNc92USPPYyVMzzI
                    ZPO9PzERPktM4b0V+OS8+AkyvitrLb6mwS4+CZvkPbPGMz4RXS2+FukGPkqXGT4MVSQ+bJqsPBdl
                    sT3sCzg+Jld/vSlZwL2Xtoe73PGnvcy81TztmAk+Ligtvt5I7z2HTOM9aWDCO7mBDj2XM/S6qJBp
                    vehjlbwYyZe9BULhvXOVsT0h4xq+1CYfvpZAvj2c79U9KDpkvWIshD2lYCm+FkkEPvck47wRnFu9
                    P3dfPK0F0r2Luus93Q97vR11lT27J6G9lu00vROi0r2blBo+t3eHPR1wDL7ekgq+DKv2PQfd871J
                    kBq+/cmEPCBQEL7y+TS+kt0ePhxiaD198a29+4rEPVdUir1RaBU+OrWePZ2vF71yqjK+tI9rvUGk
                    wD3tuxk+V82KvciXR70YxxE+95mCPSbjKL5sINi8euqZvHVZq7s4CR0+T+PGvRM04D3LdSI+3mSS
                    PA52NjwqMBc+3FDGvQC4+rxQe6i9m3ddvTr3s7yB2/w9aJnBOzFZrj1QmAY90AYmPc2vDj3weTu9
                    btIHPcCfDD5SXSE+NzENPRqM6D1/a5Y8bJ6OPW5tjb3pLRU+nQ4zvhukoLuNu/C7CGvrPdNuhr2J
                    ZoE8Tx9avYTDIz6P8Oe9KK85vnefsD1HnvK9A3H2PYzcXb2yvtq97hw3Pk9iZryPxNy9xFQ1vGXb
                    VrsdRJy9E1HCvZf6y7sgFSO9dgT+vTEjOzyavZS9B9TiveYk67nE94083XUEPiwLHb5VnRm+BWEi
                    vnpNJb2rwDE+loClvXIqHD52kfU9uu/OvarjoD35LUW9gSz0vdbrDD71FQe+KogZPvgV0b2hGBk9
                    YQksvqL3JL6DPrW9LMT5PF8/Jj7qBoI9gZyVvevzHr5FWgU+naelvTy4Gb4ceC4+biqHPR/kBD1j
                    qW09WwHrPb//+D02jto9Pb0gvjqn8D0sGt09XG/GvRJwIz5ICxo+5lJIu4KvgT1Mz/I8+PY3vptS
                    6T2uXA0+nRvTvQVxiL1DCqq92tiwPSBLq7zGHtM9U+MBPRl+Or6MGj28ax84vu1thD0wyje8tUgg
                    PvQA0j3kCk49C1YPPvaPFr6svCW+5WajPCPAfj1dZlm8
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzUzNjk5MDQwcQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTM2OTkwNDBxAWEuHgAAAAAAAABHESO+hAkjvnFbkr0i2Lq9D3pWPQ1kC77xwgc+Xg0fPqbw
                    1TzmvJi9bSLsvWETIz5dANq7Ia/8vUMaAD4AXKe9Dgc4vp+8FD4lkBi+n6gxvdERhLy640I9Ctuo
                    PO1aNT1YDgg+v9oLvt6HOr2SDtC9ojUhPidv+r0=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: true
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzUzMzEzNzI4cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTMzMTM3MjhxAWEuHgAAAAAAAADpQwe+XFg5PtILjLwOLbI9NecyvpOixz043ri9bukvPhdl
                    N72/Fma9xRIFvQ1NJz0+1o691z8vPuIGTbwG3bm9amzTvTAPJD5CNuw9dus1PjyKED5PibQ9cOYk
                    PrHo1D30rEW9lgXSvRFpXTxjJe69VkCVPV68Nb4=
                - 0
                - !!python/tuple
                  - 1
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzU0MTE2NTEycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTQxMTY1MTJxAWEuAQAAAAAAAADCnPm9
                - 0
                - !!python/tuple
                  - 1
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 1
        training: true
    - - decision
      - !!python/object:torch.nn.modules.activation.Sigmoid
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  pas_de_temp: 2
  training: true
forcasting: false
learning_rate: 0.001
