backbone: !!python/object:__main__.Rnn_classifier
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1Njc4MTI2NTkycQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    OTU2NzgxMjY1OTJxAWEuHgAAAAAAAAAEWfE+qnUavyj7AD/0+Ds/QikmP3AmX74Aj2e9cIikvrCQ
                    oL2YyXO+7ExZPyQlcT84vfa+kMr6vlDjmT2YIOM+pJ32vng7br8w+Kk9QEAKvRAlDr56eEE/gCUA
                    v2isCb76VwC/do1Av9IKYj/KfA+/mBCZPgBEdrs=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1Njc4MDQ1ODU2cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    OTU2NzgwNDU4NTZxAWEuHgAAAAAAAAAUn8G+eONsP7LSQL9eFxW/9Og/P/R4IT/U1zg/0IGdPQC3
                    ZD2S7yo/HH42v6QgBz84XKm+nJMKvyoFRb+0uqI+kNQEvw6QAz+sZF6/IGZ2vzRXgT5akVs/9qdM
                    P9B3Ib4AUZY7EOf/PWyeJ78Yzqs+QPnNvFySVb8=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: true
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1Njc4OTk5NDg4cQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    MDk1Njc4OTk5NDg4cQFhLoQDAAAAAAAAIL8CvuNBrT11JRi+nbOPPaRxpT2YzzI+O6SZPaE5Mz5G
                    gNy9Jtg4vlTL+T0m7dm8O1HSPbsr7Tw0oK89eAdOPSy0H7455gG9BpwHPsKCvr23hRE+4QCmu8EM
                    LL56zTS+u6WpPYojMj1VC5s9fzf8PSt/aj3HW289JemMPCT5Jj6xQfY991cpvr+XLD7Una69KpXU
                    u8XIuT3oWuA9/gq4vaOpA70SrzS+bVnFvTBoLz6XhCi9NtohvvWSmr1E2JM9UpUgvo3JzbwEEem8
                    xwqWPZIQuDz8ML49jsiePbQiSr3zeu87JoA1vQ3Qr70v7y2+Fm2+vD8pBz6Xzro9UBrXPbWZRr3k
                    /4c99uoOPvdOn71/qZe8lbyvPZl+Hr7ol+Y9e28NviKuyj0RM609ypkAPisbXjxK3yS+0/LsvdUP
                    Er2PqGg9xF33PHf2ij0poMS9DjqdvZRBHr57qXI9R9S+vSm0vD3SU7k9UtSCPB65GT7PNQS+i4kM
                    vioH1z3VKx4+BOMTvqnIEj62zy4+XDYJvjuaHD6GSgK+toeKvC9kRLwGQAi9Jwz6PWIjYT22dY+9
                    U8EmvgXK4r3rHu48CEMqPUJKMj6zQAI+ekryu/0Ojz2/AGA9n+oxPcOkwj36aie+IT/xPTPj1j2U
                    eQ++8+4IvkbX9b1MXAG+SVgQPMXnmT06jQ8+HUwRPavv0r0Jt5Y4T7G2vShkoD289Pw8Cdv0PT4V
                    2T1NDc880vcUvfhISL0UyDA9UdI6voRCOj6eBDK8S3PWPd2xzbsQdgk+cX6pvbTR2T33raS9FVut
                    PX9o0rxresa9pIiavaoi5L3Ecp08BZGsvRz6Fz7AMAw+Z8JkvbpSyL2zABk+HVEIvTTZPT3KdqM9
                    SFVSvVRJA77AFfO9A4wGPd5wI72j2NS9p5eRPX/t6b1gRhO+ZgEbvmI/gb2G9ci8ghioves87r2c
                    rCw+u5zDvZuVCb7rawK+LhAEPjtaFb0J5+88LOB/PWu1nb33kAy+znMFPcKZ0j1emhm+okLcve5B
                    iT27JgA+W/VXvTGTMb0GN349W6nEvdzho7zPHvM81X2SvOo20TyaBb49FZfpPYx6p72IhBA+SEXA
                    PddC7r19KfO8nyr3PWyxED7FBhC+ooGdvTQmgr3gx3C84CGavWmvuLlCEie+aEE7PFofVb19d+o9
                    foi9vRPW8j0p7LG9SJ45vt7s8z3KiKs9QMYYPsVePDw+Byw+LFPhvVfNUDzTwYm9XGI4PqASez0N
                    eCi+atgDvtFULr685tk9veWHPEoTFz40cCi+Wb/9O5XkOj6LCwY+W51zvWEnTb0eX4W9DYsivtGg
                    A745jQG+UPxdvW7Xrr34GZC97c0gvoUx2b2gXwC8RH1PPf0+Ir04Iim+pwPsPZs52D3Ok4k9ylTZ
                    PJwLsr2xAr48mQQZvk5UFL0jPzQ+/TTEPS8aIT1iL049WZYlPfELxD2ejjg9/nwlPWQkGD0vAdY9
                    ZVdQu5g8H70AwR++BinUvQ7jVL2roZ493a29PWexAj3a5ek8D1PsvFRtlD0Kcqw9o8MTviiiIT1J
                    B4c9wkvwPeCfr72LHVs8YWY4PvPjgDzGWEQ8O+b4PeL1Ab7tR7E8HB0bPY3pwz2uRG890vpkvbnR
                    I73xAcI9TES8vL2DELuqqeS7GgDhvb3JOT2HTKu9cCIyPugs472r0929PMXyPUxv/L1diDE+lsRz
                    vYr5Lzz7m7K9dpUPvnoNhj37fSo+j/oMPY22yT0n8bk8Phh1veWzGr645Bc+juahPaeBH74Lmye+
                    nGwtvd8QQLybX3U9VYT6vfv9A74IEN68T1cbPrr54j3NDQ+9qxHVve0qs73OejC9AHOiPUIrib2I
                    r1a9zPAjvnFsMr7LwBo9eG/BPfmPP7w55cI921WfPH1e1b1H6rE9yDEYvr8mjz3VH/a9BX8rvTTA
                    jb2XN6E9mgTpvRLTI70WLpA9lYWkvLp9lL2PQjM+mqQsPm15Fz5LPTw9o4SlPWsQ0z3ExKs8vBMw
                    vmU3Zz3vqsG8mhWpu6s2hr2gsQQ+oiESvCCLmb1oRSu+F606vqU6NT6xCB2+nJoDvhr2Mb47xtC9
                    A4nXPStDBL7SSC2+gOFlu6MrMr6i87c8exiEvQoxbjzVD/E9b8SIPEGKhruZzvQ9NKAnvh0w6rw+
                    h4k887z5Pc5Dez0/PZk9PmM/PHKf9Dy7Qfs9mTwDvtKJETwxdfu9r4UGvtFjxL3KzqO9WfUuPsgM
                    LT7PsAA+Hm6DvSOZnzziEzS+Zm7QuRcmtD0DvXu9CtpJPWWgqj2JTLy9cAEKvgWk6T3eYos99sSs
                    u1VoKL7586U96IFDvU6CKb6Kg/m84s8JPio3BL5BZwK+6dQhvqqDsj3IyCG+izJuvd8ND75XP548
                    cj19PZJRAT7ghRG+Cvosvk8sGD6Zoq69nXMAPgXYtzy+Ha69rRXAPbZPLr4/cNY9MtJkPfcaN72K
                    P9U9lA3oPXWjnb27gZE9UgwqPkRcTDtPLeC9v2u5vcJlMz4J9m49nXmBPDozcb0XNKy9BEOUPaVF
                    Aj6nBw2+Cacgvr4nE75QHJE94O0ZPuLter2y5t69xaC7PeX0BL4rdbQ98XPBvS4k9bwQaCu8Lc9w
                    vVRcFT2KUzk+pk7ZPfakyj2fvLO90dBMPaum6T124gu+BdvJPfHwG71EBr89JGAQvhIa5zqy3Bq+
                    dOXUPPTQ+TztngW+t2TGPJdXFz6t2QO+W0UfPZHhHz5GdIW91Og2vgFTBj7uY9+90ySRPeXyNb7X
                    8F8944EqvqykJj6l5iS+ZAgSvm0f3j1nQas80FMyPnJrLb4Q09U98t8SPXpQJD6pLBe+OS+nPeld
                    V71vMwQ9hxXcvCuQ7b195pg8xeEivgtpEj43RgS+b3dnvdC8VryS1Ai9TzkXvhBSwT19yNM9qQcz
                    PuQ2yr1pFru8/JESPV6+OT5MvJ27s3z7PVe7AT6tpeY9oiV+vS/Gwr21w5e9ATz/vaQyDz4+KZy9
                    DZC+PCXupb1S4Qs+vlc5PmXA/L3sYcS9ubeyvYGRMz5GPCo9XIO6PUCJtz10ii0+qpFmvUNFBD4T
                    izg+JAQAPk5j8ruQXSS+j78MPqYuIrwHYOC6wUvTvAK8Gr7/JoQ8ajRxvZSQVL1GGCY+mP0+vaI8
                    BL40bjY87cInvlfizr0WQx0+wvsOvtW1Ej7YJuK9gN8kvRWB0T0DOYq93KXmPAEaF74yqgc+Occr
                    voPDPr3qNc89OsWGPcQUs70jSpQ9F4dLvTmzOD5UOyY9tXz5Peobpz26pgU+SN0vvlViID2SH6Q9
                    /4XWPHeOn72LJKA9hRCJPNzNE7726OA7pXYmPkk7Hb2GKRY+ahMNPuQONz6PM/s73PQnvYBgxbw+
                    vys9DoqPPYsn7rsi+jI9sd86voka8b07mcS92/QxPjFgET5uyzY9QZ7hPGVUtL2XW/G92QhxPVBd
                    AT7tRyM93MDuPeXwjb1+99i924lFvD78N74ALNQ9nAFFPdWc7Tzza589i4crPtTGvD16NWq9oOTg
                    vBGP4L0CRCu+78spvkWeAb7rm9o70vnpvaPMGD6T94C9vSIzPt6fDD4pTxi+7tZgPcww3D2bf0W9
                    mlUaviMa+T3y0dI9H6UtPpukDj5y31090fmbvU8G4TzNQgY99hN/vWdc6LzArlG9MqsLvvz3i71L
                    cQs955uIve/tpz0EUBU+aIXtPSoNMr6AUSG+Xp3hPSSJ9T0c1xg8SCczPmxUKb5VeyO+/7eBPRHj
                    G7trTpg9nz0DvkIpJbw5Hgq+bybXuxojlD16cvg9+dliPaTbwL2zP8A9xG5CvbzADr2BvCa+qtb0
                    vdacJ70vDAU+JIGVvQroib2PCiM8DmygvI4mnj13suW9kag6vigqMr4eHty9GNQBPs6XqD0vrxS+
                    RXwPPoad5D00zBu+3zI4vSP0OT6CXAi+x3AnPm9af73jLg6+rztAvEqwL76cTfu9HPRyvUXaND4/
                    Gx4+sGFevWKjVD0ju5A9Om/nve2YMzyYhjG+StI1Pm/uij2u2S899McpPbguxj1ZDhI9xAmavbNY
                    9D2oaRW+robIvYZPirwCDSC+Lq77vS5rLD260Qs+dZhLPbojhr3rmy09j84QvqLHDb2Pgqi9H5le
                    vWodNrzuv3Y8JyUzvWW36D1VbcC9/J8NPgAmij1Syvg8/YaFPTjDij0XeDq+TTSLvZXiFj4m4qi9
                    z0yfvZnDqj3narU87ZQzvhIkXj0RH9w9d8qYPNhMET7g0um9g3SaPVYmy705UDU+6TuqPdLj373z
                    lg8+MY34PbeXYL08ibq8ycSWvax3KD4a+TY+BZEHvkaD/70yqHM968JoPcQFvzzVMuC9+2QnPuQY
                    9DwOMVM9sE3wveb5Nr5HXIU7BQIYPYVarzxloYa9LbmRPbIJyz0BwT69CXjAParJ4j23tCa+Me6R
                    vOdl4j3frQq9KD1gPDxTKj3sLIU9U39GvIc3Lb2VXGO9KtvAPcTriL0b7/u8K6mRPWRCET4Z7Nw8
                    TbQDPrSbGr40lQq+Plj0PdMcRr08e/m8SbxLvbH5FL5Adjq+CY8EPsRUdT3DtMo9ZQaHPS2cEj6z
                    uDW+g/x3PAW5QLt6uLq8vyx/vVyDxD0a/Dm+rcRzPHsuB7zUOiK+JDKjPdyxlL2/fTU+U1igvdrI
                    M7yZCxm+ai8xPXSg2LwpcjK8tNqxPcWtNL5yeCC9bxawvOciDL7/WNG9/QKbPf2vsz3gRhe+WwZe
                    PKN0mj25iuk94wTDPdyjorxYFCG+kY8PvUX4Izznhni8
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1Njg5OTg5NzkycQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQw
                    OTU2ODk5ODk3OTJxAWEuHgAAAAAAAAAL69490AwVvhHjOL7/lFW9MuCPvRJ99r27acs9LX7yvZNI
                    Gj6fC4S9LNcYvg0uy72KUM29/ekBvnhS9L0RxPU9/dsLPiR4iz3FghS+ZiMxPuTr4D2X6Eo9W3/Q
                    vYS/K702/ro9YeXWvV4YgT1qDpw98T6ivQDnMz0=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: true
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1Njc4MDI4NTQ0cQJYAwAAAGNwdXEDS5ZOdHEEUS6AAl1xAFgOAAAAOTQw
                    OTU2NzgwMjg1NDRxAWEulgAAAAAAAAAllsY8nKAKPr9fOrouhKS9nS3DPQgQND1u/go9t5Ynvpl4
                    yL3IG/I8Z00jvqjR+L0sK7k9RHl/PORNMD6i1hC+lzjjPVK4zb11sKm9hV0WvsIF9T1yJJc9NcUN
                    voasNL24+ze+/Q+7PbED+b3Qai2+NqsfPWdgoD1bMM+8QgcIPn4eUT3t3BC8Yxk2vu07ob0DoKE8
                    xX5VPJ5QsL2vmPI9d4whvpOw6T3S5aA9xdSOPZZBxLwa9c+9A8EWveuh3b1bFri90M5wPMwNH77c
                    z1c9jO3PPNO+Hz5xnCw+g8CsPVut2D0VWvi9IWVZvVpasLyL9Qs8W2OfPdil5T1lRDY8fPstPl/o
                    Ir0N8MI8zkIivlHJCz0x2CQ+hUkzPreRML7XsCs9DoeEPcvpPb1G8jM+VAccPhyJOj4S1B2+YsoE
                    voJaAb1n2RU+nGt1PbRWkr35W3s9pEvevXb7IL7lhuu9cFY0vs/UM71BpyS+kI0Uvet7Nj0d5Dg+
                    AexOvenY+724upU8wHQHvaogcj1fUP88axJGvIfABb7fhAK+8hOwvTl84z1NGBw+FDSpvbxLE750
                    UBQ+2DfMvYDFET2tdg69fUs8vW18Lz62L0q91hiZO/SdOL5riqu9wYrvvSvYEb4lwR4+fsmFPVEX
                    ML6i0TU+h8Ewvdaah72IQKA9kxugPQO80r2tmcC9IEVoPCe/T70Id3+9+0FqPXrMYz03NRE+lpQI
                    vorVDL17f8E8TbWSPSAqBr4gI609aJi7PF46sTzdlgS+GumwvWe9Mj1p5ti9Xe6jvZswGr0=
                - 0
                - !!python/tuple
                  - 5
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0MDk1Njc4OTk5Nzc2cQJYAwAAAGNwdXEDSwVOdHEEUS6AAl1xAFgOAAAAOTQw
                    OTU2Nzg5OTk3NzZxAWEuBQAAAAAAAADEHiw+ma9ZvQIgKT1FQuC7Whs5Pg==
                - 0
                - !!python/tuple
                  - 5
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 5
        training: true
    - - decision
      - !!python/object:torch.nn.modules.activation.Softmax
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        dim: 1
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  training: true
learning_rate: 0.001
