backbone: !!python/object:__main__.Rnn_forecasting
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - x
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzU0MzExODA4cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTQzMTE4MDhxAWEuHgAAAAAAAABoUhE+PEHlPsINNT/kO2S/QMpVv+RaSz9SlgA/CKFPP7DF
                    1D5MzUA/nLKxvhgcSr7YqPI+uIpsPpCHOT4WRTo/GMMpvlC82D44qEs/SgQev6AlFD4Ucvo+7ihl
                    vyDgOL24/Q4/RqMkP9j3KD9cI3C/WMRWv3KxeL8=
                - 0
                - !!python/tuple
                  - 30
                  - 1
                - !!python/tuple
                  - 1
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzUzMzA4Mjg4cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTMzMDgyODhxAWEuHgAAAAAAAACAMAi/+nQbP3grNz+whmU+aC4yvmxwEL8+kC4/nFtwv1y2
                    WD9Qcoe9WD6gvh4MUD/8KcO+0tkiv9IuXb9yCz2/qMGBPs6ydL/Edtw+pMqsvgZ7fb82phK/ytZV
                    v/h7Fz6SIX0/bLqnvrBzYT/4FkK+AIVtPEahQz8=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 1
        out_features: 30
        training: true
    - - h
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzU0NTQ1OTIwcQJYAwAAAGNwdXEDTYQDTnRxBFEugAJdcQBYDgAAADk0
                    ODQzMzU0NTQ1OTIwcQFhLoQDAAAAAAAA+fItvv2oh70Jxg2+1GE/vZBpCj2AxgO+l8vPPA03Cz5+
                    gkQ9IaA3vV//GL6YV+M9E+0sPtnMTL0dsQK+msYyPWsNAD6k7es8M14JvveUJr5/uig7DBcMvSG4
                    uDzfvDI+wTdJvNbcnD0eoRs+duDovcdLRTyrS5G9RjyiPbiPFL4b6cC9WJARPoO/Lz6cukS95IIj
                    PlD6Nb7y1FI7JBcJvmlCDj7leDa+r06kPSS4Lj5f23K9F/f6vW9XED60Q8M9PmmpvX4OiT2AcYw9
                    7py5vXu3f73DSbS9L/aSvbajsz0QwKQ9K4euPfRs1DxzFP49mKe8vXqNMj6ejrg9/AYoPmUwMT7M
                    dQq+ThQHvnISQL3wx6U9aEl6PGjxAj4qWQm+08WLPZcmOr6zpxe+sHYfvoFZ9r0GDuw9TUxLvQMP
                    0r0zZQW9EL8XPSWbgzsePxI9hYUmPrnKgTxH/jG+6LcXvu68Eb682OA9fVYdPa3+pD083669PaVv
                    Pb50Gj7zeP88svuAPU0bJj6OHJI9X8E1PZA4YTwRSIW9x2jiPSFFOz0TETU+ZOaOvFZVqz3G+zA+
                    hT7ovR9gsr3zHyW+DYAwvjCq8r1kKjk+lNIRvKGig7vmKrU9vIMvPZ+wCT5L+NW9p7DMvaSyJz6H
                    /bs9wsSYvPOGdT1Zx9u9mffnPU2QF7uE2Uk9M++ku1or9L0OSSw+Qq4mvn5xjT0rwte9KaPZPCpS
                    CT7jnO+9Kawcvl7lCL5PBXQ81NhoPVPiybx4K9G9u+k6vrmOML5404q9qvTmva0nCL647Vk9XSTE
                    PR3JNr5+sWe9n/QSPsXCMz6CHh0+HUe7PYzDKr6svBe+Wl+mvQBNEL4CVIM9yu0qPop18r2onie+
                    QBX7PH/Bsb12wpo9QGsmvqxe9T20mEO90Nq3PSgrCj6K9LG9h7vzvVW4Pr05XBQ9NOzzPEvsA76P
                    8TQ9M3oCvf4QQryOZ4q98XMdPnnq8Lz2O+Q9dNEMPQ+Hdj2G7DC9nMgkvgbV2T0PsAg+ChkhvhsF
                    ID1pa6I9IFzEPWf2572l1449gRpIvYx/lj01Tfs8dBrGvPIoMb6MrxW+xfdxu0/SFj0J1Ae+Mu8R
                    vuvArj3P/4Y9VH9DPE5Ojj2x23I98UoSPjJNlL2qYRe+oGEgPi4QIr3wgrY9DJI0PmS5I77t1RK8
                    xjuxvWzXCL7iOLc9mF4oPb4k073bT8m8GXAlvE1aKL1u7gA+dXcdPpFCpD3YYPc9/hnPvD5hBz6W
                    SyE+Z3nQPE+sDL4w2au90acsvbEJuL0Ftai8T5o6vfSdsT3SR3M9aujkvXPrBT55meu8HyoEPewK
                    LD49Aac9AlkOPj2zoT3oli+9pu+BvH/NDL4BNbS91oYLPt3kFr2/YNg99OjsOk+nJj5POkG9/TAj
                    PA/8vL3dRwQ+yMqsPdCaND4pRxc+LmGPPYccO7wAKXQ7BbW2PVQ4BL7ZroY9IMObvQxSjj2sC1M9
                    jmyRvSQOfz0h+ho+kIkpPo3cLb4xGn+91mYiPXF1KL4/nwG9j/O1veiHGL6aDhy+esY5Ps/kEr5Y
                    /rY7aDxPPTL9zL2Qzw6+TZ/YvRd2Cz5bdpw8huKLvXdqrT2s6tY9XrWjvXnBUDwArq+9t88tvgXX
                    Jz5o+R4+npsIvvEKsz1lViW+T45NvfJ/Ib4yTA4+T1WfPXACQb257du8minFvetDOL2tDcS9Bu4D
                    Ph3nMb7YbjK+tpI/u7izDD11i/89w9i7Pd7s8D3LLxO+XhiSPauJnT30Pqy8Rq4yPeb4Nb1jzOM9
                    a/uNPXyVjb3Zd7e9dnogvh9p7r1SqbY902ozvGrX4jxg+Y68MkcjvkZhpD3oLiY+3guGvYcNMj4T
                    seW9V6PZvH7ZIr6hdMW8VPX1vbYq071DYDQ+hHCyvUSo8z3hCkq9piDwvaXq/72n2L08kVbRPfBj
                    fr0XA++9YJkyvgnw+TyrhQU+E1dvvY8x1737peW7g6YHPgtkGz4ahEi9nqCvPSpjpz3V7m29v7SM
                    PUHGOL7YF+68Y6njPSMgNz6e6BS+TvghPi14Nj39PO891VwLvkGOaj3B2hQ+45sIPrNj1D2O5du8
                    yiKTPZY/NT1iWp49BJ0jviDj1LyPYiA+dFYAvSidxD1mor69y62IPMM5Mr6kbxA+BSufPT15jD31
                    0H49aOrjvYZGED7Jslc9wMNZPfMGwju1tAA8Li05vf6YxD0MmCa+qQECviBnLj0kQb29kwhKvWfT
                    CzziSBG+/uK5PQVRg7jp0gA+ce4HPpq/lL3cnh4++1/jvW1op70inCO+h4XvvYVHQb2IAFY9J19W
                    PW1L+j0rt0m9/ODEve6LqD0tY3S9BSXGvU3VJ76ToMK9Pyr7O4tMMr7l8Po9yFsHvnMqGL4YP/E8
                    9rEOPnX2pD2ysgY9lKVyPPhnfD0/1Ze9LJqCvWMyDr5afL09J9Lsvdy1ID14pPG8TRgMvipaEj3B
                    DE+8HvcAPrXYij17xEs9IwHEvTyyED5tUJw8G5QKvSO6CD6nKCs+4K7mPZP5XTxo8Io9i/6Nvcv9
                    IL1J3zO+9McCvhvXm7xlMPA9Qgb/PeNWsj0FKl+7+1MjPi8FJ74oFb89JYYJPvVqTb3FFJy9PFMa
                    PlZYMb5onqI916ALvjyCJjyjOvU8RIQxvcJKJT7su6+94fMnPSZM9DxSymo9MWdbPWbVwD19YeA6
                    ky4BPT70JT5l4Po9vbHYvdt3Gj0GeAO+qDfqPSwYbT2ZmqA9ZHolvXfZs7zW1c89Ee8CPKsx2T3W
                    GPU9eCZKvdeNEz6W+Qg+e6EivsmsHb4gVwI+vIlLPemAAb7b4Mq9lr8APk8Tvz1PffE9sfSBPf+a
                    A75m6MO7cH0TPWEbsj12uhO95L7evJ/87j2Frjg9T3wUvjiK0z0sgom9+9qEvXziVDw6IK29Vtbn
                    vQL92b3fJdM81gfTvApKFj0t28C93CAovpkinzwtrVy9j+zMvdt8TDxprgS+9EsWvi6YgDztOd89
                    5IvKPOPaED6BqBe+ilh3PTi5qDwMdTY7ub7iPZueKD3S2Ly9m3mbPQ8L5T0T65A5OfhCPTH+ajzC
                    0Xs9AGQovQ0DvL1gKSQ+40/6u1ikizyK7KO9tV27vZ8NtryZKhk++A8VPSkZ7z3i0Sa+4fzRPRMF
                    k7zHfgO9DokivodFTb1+Miw9siHhvbC5Uz2fb8I9hBHTPASq4L3/QyU+GskPPghpKb6KYyw+dY7f
                    vZipWT2odPS9AMWOvQfUQj2TvgO+BH3PPWCvsL2xe6g8eptHvUoQMD5sKtK5OKogPqITFj0c4hq+
                    TyCqPdUUuT1MxHU9PfwGPnr4Kz0U0629VncqPMQzeD09DCG90EUDvuVXOjz+IMe8cySfvcdS6r0X
                    0ry9VxmsuYM4NT6cYBC+d+TuPKUNRDzk8Zm9WoUNviDKkr2eTuE9PqOavDfPwD3aorK9P1DqvBMn
                    zjynag0+ElvaPXnIKz4FaQk+zb4gPpDNHD49zQe+gmebvBq37T2oMze74eE3vUZBHDpJxdi92S5u
                    vUD/IL6VNCo957YsPhB70r2Qh/A8gEd2PQRBszwgr0292LhsvUL+rbuihCq+WWWovZjzDT5j8sG9
                    utKGPVe/ST0v+/U9r1c2vrA3Gj6u6QM+mUQMvmqHIr54SKm9GmrmvXFC8rujPSg91kgUvoHxAD2I
                    +NQ9CVl1vRhhBT2whjk+TKsqvjIj9b14BPY82G1qPbUuET6rKO+9JUDHvfLhervfMwo+XqIAPjgE
                    Fb5d9DQ+JuvOPUS2073LFPA9u8WAPfgaHb54QaA831YmO4VNR71Harq9dlpdPQuvKT6ptAI+ULmY
                    Pd/m5L2cXoe9TupKPc0iCz6rIQi8vhD3PUzkvj1vMK87Arj1PVQ6Tz20MBE+Od8vPiiC/D2+ToE9
                    4ggivj8dIb6hNLw9z1TfPZaR6j1u2fW9Yt8avgQC3T1MetU7xhS5vTOJCz4+NcU9HMzYvc1FAj2Q
                    Ke69yqI0vocm/L030ji+hdS/vcAN3rtiTQ0+dfnYPeJEAb5mqjU+QFkEvchQtb0JHAI+OkQjPfGY
                    +z0Cxpq9lFJTvd0ysr2cEgm+wAanvRh83r0C1Qg+JNXTvR8iNj6ppRU+7hhTvTOabj1PDgc+4Hny
                    PcRqdT1uQkE9D+vcvchEQTyCDTe+oZAkPd1R4r1kFC0+ha9aPf/WMz74jge8tnsePt4Q6b1or5S9
                    askKvUNb/T2D5QC+qH0PPkqDRD0w8py9TI0MPi6PfL2ct1m8rgWzvTv0vL14loS9hZhfPRHMp73/
                    7NG9GHQWPjKO2DwGt7W9UrIMvsaML70o08W65bwnvs4gOr0mbpc9NT4EvQH20j0AILK8X7BfPXT+
                    mDzKuEY9VrLOPNXxMb4oWvq9jkM6PkItjrziVDq8jIAoPvl0+r1N3u47Xl3UPUigUT1+MQW+AOBn
                    vZ+2m73+dtu9IrdQvTpuMD0HEy4+T30IvsuoLr7toh+9yNgMvrpGKD6QliY+iMcRPWXbr70aAEU8
                    pqphvbdVbj3Sx7E9nwCZvc4P6T3eNI28M+HjvN3Lur1AL+y9OlEZvqJ9MDzbdh2+Q1o6vmt4yT19
                    MAq90gkmvudlsT213SA+QSA5PvIi3D2s4C++5cSYPcOsc7zqGRA9uNAYPVtnMb5djAC++skTPqnk
                    ZD3wDJo8ooRjvOLQNr6oQ3S8W0hevdamC74Hi8Q9oNthvTpI+T13rK06D94tPs9VjT1L9jC+VTBu
                    PQccFT67LZ09S4sYPSDfur0Tonm7I4e6vDvXBj23EPI9
                - 0
                - !!python/tuple
                  - 30
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg3NDYwNjA4cQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODc0NjA2MDhxAWEuHgAAAAAAAAASCu69LmLpvb946zybQRU9SeCLPQHG0T1Qwq+7p828vRT2
                    +D30owO9nsDwPbE+lz0xLzI+OwgVvV2QOT1GHMU94yh0vWWD5D0MDgK9k4mZPcswBr2a+S2+MH2w
                    PX6eCD6KaAu+vmgVvayA5j2g6AW+G1/EvU/2WD0=
                - 0
                - !!python/tuple
                  - 30
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 30
        training: true
    - - tanh
      - !!python/object:torch.nn.modules.activation.Tanh
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
    - - out
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzg5MDUwMjQwcQJYAwAAAGNwdXEDSx5OdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzODkwNTAyNDBxAWEuHgAAAAAAAADT4pS8PVG1vd2fAb7eAgc9JVirPZVc+T2NZ769f5IYPu1y
                    AT6h7ic9rXg2vppBnz3/C0o6YBZIPTSNeLy0Jxe+PmXLvKyyrTt+7ci9PnwhPqx1yj1AVAS9tKSC
                    PULGCDwKwSm90XT0vSAUmj3W9/G9UkPkPUXyMr4=
                - 0
                - !!python/tuple
                  - 1
                  - 30
                - !!python/tuple
                  - 30
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
          - - bias
            - !!python/object/apply:torch._utils._rebuild_parameter
              - !!python/object/apply:torch._utils._rebuild_tensor_v2
                - !!python/object/apply:torch.storage._load_from_bytes
                  - !!binary |
                    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
                    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
                    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
                    Z2UKcQFYDgAAADk0ODQzMzU0MTY0NTQ0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQ4
                    NDMzNTQxNjQ1NDRxAWEuAQAAAAAAAAAFAhs9
                - 0
                - !!python/tuple
                  - 1
                - !!python/tuple
                  - 1
                - false
                - !!python/object/apply:collections.OrderedDict
                  - []
              - true
              - !!python/object/apply:collections.OrderedDict
                - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 30
        out_features: 1
        training: true
    - - decision
      - !!python/object:torch.nn.modules.activation.Sigmoid
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  latent_size: 30
  pas_de_temp: 2
  training: true
forcasting: false
learning_rate: 0.001
